import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString, sanitizeUrl } from "@/lib/registry/shared";
import { directNavigationLinks, navInstanceId } from "../_shared/navigation";
import { logoMarkHtml } from "../_shared/logo-export";

export function navbarCenteredExport(node: Node): ExportResult {
  const logo = propString(node, "logoText").trim() || "Aruna Studio";
  const cta = propString(node, "ctaText").trim() || "Mulai proyek";
  const ctaUrl = sanitizeUrl(propString(node, "ctaUrl").trim() || "#kontak");
  const instance = navInstanceId(node, "centered-nav");
  const menuId = `${instance}-menu`;
  const links = directNavigationLinks(node, 4).map((link) => `<a class="bi-centered-link" href="${escapeHtml(link.url)}">${escapeHtml(link.label)}</a>`).join("");
  return {
    html: `<header class="bi-centered-wrap"><nav class="bi-centered-nav" data-bi-centered-nav="${instance}" data-open="false" aria-label="Navigasi utama"><div class="bi-centered-top"><button class="bi-centered-toggle" data-bi-centered-toggle type="button" aria-expanded="false" aria-label="Buka menu" aria-controls="${menuId}"><i></i><i></i></button><a class="bi-centered-brand" href="#">${logoMarkHtml(node, logo, "bi-centered-brand-img", "", undefined, true)}${escapeHtml(logo)}</a><a class="bi-centered-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">→</span></a></div><div class="bi-centered-links">${links}</div><div class="bi-centered-mobile" id="${menuId}">${links}<a class="bi-centered-mobile-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">→</span></a></div></nav></header>`,
    css: `.bi-centered-wrap{position:relative;z-index:20;padding:1rem 1.5rem;border-bottom:1px solid var(--bi-border);background:var(--bi-bg);color:var(--bi-fg);font-family:var(--bi-font-body)}.bi-centered-nav{max-width:72rem;margin:auto}.bi-centered-top{position:relative;display:flex;min-height:2.5rem;align-items:center;justify-content:center}.bi-centered-brand{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;color:var(--bi-fg);font-family:var(--bi-font-heading);font-size:1.15rem;font-weight:900;letter-spacing:-.055em;text-decoration:none}.bi-centered-brand-img{width:1.75rem;height:1.75rem;border-radius:var(--bi-radius);object-fit:cover}.bi-centered-cta{position:absolute;right:0;display:inline-flex;align-items:center;gap:.35rem;padding-bottom:.25rem;border-bottom:1px solid currentColor;color:var(--bi-fg);font-size:.76rem;font-weight:750;text-decoration:none;transition:color .2s ease}.bi-centered-cta:hover{color:var(--bi-primary)}.bi-centered-links{display:flex;justify-content:center;gap:.15rem;margin-top:1rem;padding-top:.75rem;border-top:1px solid var(--bi-border)}.bi-centered-link{position:relative;padding:.5rem .75rem;color:var(--bi-muted-fg);font-size:.67rem;font-weight:800;letter-spacing:.13em;text-decoration:none;text-transform:uppercase;transition:color .2s ease,background .2s ease}.bi-centered-link:hover{border-radius:999px;background:var(--bi-muted);color:var(--bi-fg)}.bi-centered-toggle,.bi-centered-mobile{display:none}@media(max-width:640px){.bi-centered-wrap{padding:.85rem 1rem}.bi-centered-top{justify-content:center}.bi-centered-toggle{position:absolute;left:0;display:grid;width:2.25rem;height:2.25rem;place-content:center;gap:.28rem;border:1px solid var(--bi-border);border-radius:50%;background:transparent;color:var(--bi-fg);cursor:pointer}.bi-centered-toggle i{display:block;width:.95rem;height:1.5px;background:currentColor;transition:transform .2s ease}.bi-centered-nav[data-open="true"] .bi-centered-toggle i:first-child{transform:translateY(2px) rotate(45deg)}.bi-centered-nav[data-open="true"] .bi-centered-toggle i:last-child{transform:translateY(-2px) rotate(-45deg)}.bi-centered-cta,.bi-centered-links{display:none}.bi-centered-nav[data-open="true"] .bi-centered-mobile{display:grid;gap:.15rem;margin-top:1rem;padding-top:.75rem;border-top:1px solid var(--bi-border)}.bi-centered-mobile .bi-centered-link{padding:.7rem .75rem;border-radius:calc(var(--bi-radius) * .75);font-size:.82rem;letter-spacing:normal;text-transform:none}.bi-centered-mobile-cta{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;margin-top:.35rem;padding:.8rem;border-radius:calc(var(--bi-radius) * .75);background:var(--bi-primary);color:var(--bi-primary-fg);font-size:.84rem;font-weight:800;text-decoration:none}}`,
    js: `document.querySelectorAll('[data-bi-centered-nav="${instance}"]').forEach(function(nav){var button=nav.querySelector('[data-bi-centered-toggle]');if(!button)return;button.addEventListener('click',function(){var open=nav.dataset.open==='true';nav.dataset.open=String(!open);button.setAttribute('aria-expanded',String(!open));button.setAttribute('aria-label',open?'Buka menu':'Tutup menu');});nav.querySelectorAll('.bi-centered-mobile a').forEach(function(link){link.addEventListener('click',function(){nav.dataset.open='false';button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Buka menu');});});});`,
  };
}
