import type { ComponentManifest } from "@/lib/registry/types";

export const authLoginManifest: Omit<ComponentManifest, "previewRenderer" | "exportAdapter"> = {
  id: "auth-login",
  name: "Form Masuk",
  category: "form",
  scope: "landing",
  description:
    "Halaman masuk dengan kartu kredensial: centered, dua kolom dengan gambar, atau latar gradasi. Terhubung ke tombol daftar.",
  tier: "free",
  priceKey: "auth-login",
  version: "1.0.0",
  defaultProps: {
    layout: "centered",
    logoText: "Karsa Studio",
    logoImageUrl: "",
    heading: "Selamat datang kembali.",
    subtitle: "Masuk untuk melanjutkan pekerjaan Anda di dasbor.",
    emailLabel: "Email",
    emailPlaceholder: "nama@perusahaan.com",
    passwordLabel: "Kata sandi",
    passwordPlaceholder: "Masukkan kata sandi",
    buttonText: "Masuk",
    showRemember: true,
    rememberText: "Ingat saya di perangkat ini",
    showForgot: true,
    forgotText: "Lupa kata sandi?",
    forgotUrl: "#",
    footerText: "Belum punya akun?",
    footerLinkText: "Daftar gratis",
    footerLinkUrl: "#",
    splitImageUrl:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=88",
    splitImageAlt: "Ruang kerja tim yang sedang berdiskusi di depan papan putih",
    splitTitle: "Tempat tim mengelola 120+ proyek digital.",
    splitText:
      "Karsa Studio dipakai 40 tim di Indonesia untuk merancang, menyetujui, dan meluncurkan website dari satu dasbor.",
  },
  contentControls: [
    {
      key: "layout",
      label: "Tata letak",
      group: "Tampilan",
      type: "select",
      options: [
        { value: "centered", label: "Kartu di tengah" },
        { value: "split", label: "Dua kolom dengan gambar" },
        { value: "gradient", label: "Latar gradasi" },
      ],
    },
    { key: "logoText", label: "Nama brand", group: "Brand", type: "text" },
    { key: "logoImageUrl", label: "Logo (gambar)", group: "Brand", type: "image" },
    { key: "heading", label: "Judul", group: "Kartu", type: "text" },
    { key: "subtitle", label: "Penjelasan", group: "Kartu", type: "textarea" },
    { key: "emailLabel", label: "Label email", group: "Formulir", type: "text" },
    { key: "emailPlaceholder", label: "Contoh email", group: "Formulir", type: "text" },
    { key: "passwordLabel", label: "Label kata sandi", group: "Formulir", type: "text" },
    { key: "passwordPlaceholder", label: "Contoh kata sandi", group: "Formulir", type: "text" },
    { key: "buttonText", label: "Teks tombol masuk", group: "Formulir", type: "text" },
    { key: "showRemember", label: "Tampilkan 'ingat saya'", group: "Formulir", type: "boolean" },
    { key: "rememberText", label: "Teks ingat saya", group: "Formulir", type: "text" },
    { key: "showForgot", label: "Tampilkan tautan lupa sandi", group: "Formulir", type: "boolean" },
    { key: "forgotText", label: "Teks lupa kata sandi", group: "Formulir", type: "text" },
    { key: "forgotUrl", label: "Tautan lupa kata sandi", group: "Formulir", type: "link" },
    { key: "footerText", label: "Teks bawah kartu", group: "Kartu", type: "text" },
    { key: "footerLinkText", label: "Teks tautan daftar", group: "Kartu", type: "text" },
    { key: "footerLinkUrl", label: "Tautan daftar", group: "Kartu", type: "link" },
    { key: "splitImageUrl", label: "Gambar sisi kiri", group: "Panel samping", type: "image" },
    { key: "splitImageAlt", label: "Alt gambar", group: "Panel samping", type: "text" },
    { key: "splitTitle", label: "Judul panel samping", group: "Panel samping", type: "text" },
    { key: "splitText", label: "Teks panel samping", group: "Panel samping", type: "textarea" },
  ],
};