import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/** Dashboard admin klasik — terinspirasi dari template "adminator". */
export function createAdminDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Adminator",
      props: {
        brandName: "Adminator",
        brandTag: "ADMIN",
        userName: "Rudi Hartono",
        userRole: "Super Admin",
        linksJson: JSON.stringify([
          { id: "ringkasan", label: "Ringkasan", icon: "layout-dashboard", active: true },
          { id: "pesanan", label: "Pesanan", icon: "shopping-cart", active: false },
          { id: "pengguna", label: "Pengguna", icon: "users", active: false },
          { id: "laporan", label: "Laporan", icon: "file-text", active: false },
          { id: "pengaturan", label: "Pengaturan", icon: "settings", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Adminator",
      props: {
        title: "Ringkasan Operasional",
        breadcrumb: "Adminator / Ringkasan",
        searchPlaceholder: "Cari pesanan, pengguna, atau laporan...",
        actionText: "+ Buat Laporan",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Pengguna Aktif",
      props: {
        title: "Pengguna Aktif",
        value: "12.480",
        change: "+8,2%",
        trend: "up",
        subtitle: "dibanding minggu lalu",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Pesanan Hari Ini",
      props: {
        title: "Pesanan Hari Ini",
        value: "342",
        change: "+23",
        trend: "up",
        subtitle: "pesanan masuk hari ini",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Pendapatan Mingguan",
      props: {
        title: "Pendapatan Mingguan",
        value: "Rp 98,6 jt",
        change: "+14,1%",
        trend: "up",
        subtitle: "dari 7 hari terakhir",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Tiket Dukungan",
      props: {
        title: "Tiket Dukungan",
        value: "27",
        change: "-12",
        trend: "down",
        subtitle: "tiket belum selesai",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Kunjungan",
      props: {
        title: "Kunjungan Harian",
        chartType: "area",
        dataJson: JSON.stringify([
          { month: "Sen", revenue: 1280 },
          { month: "Sel", revenue: 1420 },
          { month: "Rab", revenue: 1360 },
          { month: "Kam", revenue: 1590 },
          { month: "Jum", revenue: 1740 },
          { month: "Sab", revenue: 2010 },
          { month: "Min", revenue: 1880 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Kategori Penjualan",
      props: {
        title: "Kategori Terlaris",
        chartType: "donut",
        dataJson: JSON.stringify([
          { label: "Elektronik", value: 42 },
          { label: "Fashion", value: 28 },
          { label: "Kebutuhan harian", value: 18 },
          { label: "Lainnya", value: 12 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "data-table",
      name: "Pesanan Terbaru",
      props: {
        title: "Pesanan Terbaru",
        subtitle: "20 pesanan terakhir yang perlu dipantau hari ini",
        rowsJson: JSON.stringify([
          { id: "ORD-5521", customer: "Budi Santoso", item: "Headphone Wireless", amount: "Rp 1.250.000", status: "Proses", date: "20 Agu 2026" },
          { id: "ORD-5520", customer: "Sari Dewi", item: "Sneakers Urban", amount: "Rp 890.000", status: "Selesai", date: "20 Agu 2026" },
          { id: "ORD-5519", customer: "Ahmad Fauzi", item: "Smartwatch Fit", amount: "Rp 2.100.000", status: "Proses", date: "19 Agu 2026" },
          { id: "ORD-5518", customer: "Maya Anggraini", item: "Tas Ransel", amount: "Rp 640.000", status: "Dikirim", date: "19 Agu 2026" },
          { id: "ORD-5517", customer: "Rizky Pratama", item: "Keyboard Mekanik", amount: "Rp 980.000", status: "Selesai", date: "18 Agu 2026" },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-activity-list",
      name: "Aktivitas Terkini",
      props: {
        title: "Aktivitas Terkini",
        description: "Perubahan terakhir di sistem dalam 24 jam terakhir",
        items: [
          { initials: "BS", title: "Pesanan ORD-5521 diperbarui", description: "Budi Santoso mengubah alamat pengiriman.", time: "5 menit lalu", status: "selesai" },
          { initials: "SD", title: "Pembayaran diterima", description: "Sari Dewi melunasi pesanan ORD-5520.", time: "32 menit lalu", status: "selesai" },
          { initials: "AF", title: "Tiket #482 dibuka", description: "Ahmad Fauzi melaporkan kendala pembayaran.", time: "1 jam lalu", status: "proses" },
          { initials: "MA", title: "Stok diperbarui", description: "Tas Ransel berkurang 12 unit di gudang B.", time: "2 jam lalu", status: "proses" },
          { initials: "RP", title: "Laporan mingguan dikirim", description: "Laporan penjualan dikirim ke manajemen.", time: "4 jam lalu", status: "selesai" },
        ],
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "form-add-data",
      name: "Tambah Barang Baru",
      props: {
        title: "Tambah Barang Baru",
        description: "Lengkapi detail barang sebelum dipublikasikan ke katalog.",
        fieldsJson: JSON.stringify([
          { label: "Nama barang", placeholder: "Contoh: Speaker Bluetooth" },
          { label: "Kategori", placeholder: "Elektronik" },
          { label: "Harga jual", placeholder: "Rp 750.000" },
          { label: "Stok awal", placeholder: "50" },
        ]),
        submitText: "Simpan barang",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
  ];
}