import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/**
 * Static admin dashboard with realistic operational data. The builder groups
 * these dashboard nodes into a desktop sidebar, KPI row, chart grid, and
 * activity table automatically.
 */
export function createAnalyticsDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Admin Karsa",
      props: {
        brandName: "Karsa Studio",
        brandTag: "ADMIN",
        userName: "Nadia Ardelia",
        userRole: "Operations Lead",
        linksJson: JSON.stringify([
          { id: "overview", label: "Ringkasan", icon: "layout-dashboard", active: true },
          { id: "projects", label: "Proyek", icon: "bar-chart-3", active: false },
          { id: "billing", label: "Keuangan", icon: "credit-card", active: false },
          { id: "clients", label: "Klien", icon: "users", active: false },
          { id: "settings", label: "Pengaturan", icon: "settings", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Ringkasan Bisnis",
      props: {
        title: "Ringkasan Bisnis",
        breadcrumb: "Karsa Studio / Admin",
        searchPlaceholder: "Cari proyek, klien, atau invoice...",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Pendapatan Bulan Ini",
      props: {
        title: "Pendapatan Bulan Ini",
        value: "Rp 86,4 jt",
        change: "+12,8%",
        trend: "up",
        subtitle: "dibanding bulan lalu",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Proyek Aktif",
      props: {
        title: "Proyek Aktif",
        value: "18",
        change: "+3",
        trend: "up",
        subtitle: "proyek berjalan minggu ini",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Retensi Klien",
      props: {
        title: "Retensi Klien",
        value: "92%",
        change: "+4,1%",
        trend: "up",
        subtitle: "dari kuartal sebelumnya",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Pembayaran Masuk",
      props: {
        title: "Pembayaran Masuk",
        value: "Rp 47,2 jt",
        change: "+18,7%",
        trend: "up",
        subtitle: "dalam 7 hari terakhir",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Pertumbuhan Pendapatan",
      props: {
        title: "Pertumbuhan Pendapatan",
        chartType: "area",
        dataJson: JSON.stringify([
          { month: "Mar", revenue: 42 },
          { month: "Apr", revenue: 51 },
          { month: "Mei", revenue: 48 },
          { month: "Jun", revenue: 64 },
          { month: "Jul", revenue: 73 },
          { month: "Agu", revenue: 86 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Sumber Prospek",
      props: {
        title: "Sumber Prospek",
        chartType: "donut",
        dataJson: JSON.stringify([
          { label: "Referensi", value: 38 },
          { label: "Website", value: 27 },
          { label: "Komunitas", value: 21 },
          { label: "Media Sosial", value: 14 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "data-table",
      name: "Aktivitas Proyek Terkini",
      props: {
        title: "Aktivitas Proyek Terkini",
        subtitle: "Ringkasan pekerjaan dan tagihan yang perlu dipantau hari ini",
        rowsJson: JSON.stringify([
          {
            id: "PRJ-084",
            customer: "Pesisir Coffee",
            item: "Website company profile",
            amount: "Rp 18.500.000",
            status: "Proses",
            date: "14 Agu 2026",
          },
          {
            id: "PRJ-081",
            customer: "Sana Living",
            item: "Sistem identitas visual",
            amount: "Rp 24.000.000",
            status: "Selesai",
            date: "13 Agu 2026",
          },
          {
            id: "INV-213",
            customer: "Arunika Health",
            item: "Termin kedua strategi brand",
            amount: "Rp 12.750.000",
            status: "Proses",
            date: "12 Agu 2026",
          },
          {
            id: "PRJ-078",
            customer: "Pohon Rupa",
            item: "Kampanye peluncuran produk",
            amount: "Rp 9.800.000",
            status: "Selesai",
            date: "11 Agu 2026",
          },
          {
            id: "PRJ-086",
            customer: "Kabin Kota",
            item: "Workshop arah brand",
            amount: "Rp 6.500.000",
            status: "Proses",
            date: "10 Agu 2026",
          },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
  ];
}
