import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/**
 * E-commerce store dashboard with KPI row, sales chart, order table,
 * and a filter + activity column. Widgets are grouped in grid containers
 * following the analytics template conventions.
 */
export function createEcommerceDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Toko Senja",
      props: {
        brandName: "Toko Senja",
        brandTag: "PENJUAL",
        userName: "Dewi Anggraini",
        userRole: "Penjual",
        linksJson: JSON.stringify([
          { id: "ecom-1", label: "Ringkasan", url: "/", icon: "layout-dashboard", active: true },
          { id: "ecom-2", label: "Pesanan", url: "#pesanan", icon: "bar-chart-3", active: false },
          { id: "ecom-3", label: "Produk", url: "#produk", icon: "credit-card", active: false },
          { id: "ecom-4", label: "Pelanggan", url: "#pelanggan", icon: "users", active: false },
          { id: "ecom-5", label: "Laporan", url: "#laporan", icon: "settings", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Ringkasan Toko",
      props: {
        title: "Ringkasan Toko",
        breadcrumb: "Toko Senja / Ringkasan",
        searchPlaceholder: "Cari pesanan atau produk...",
        showSearch: true,
        showNotifications: true,
        notificationsMode: "panel",
        notificationsJson: JSON.stringify([
          { id: "n1", title: "Pesanan #2048 menunggu konfirmasi", time: "2 menit lalu" },
          { id: "n2", title: "Stok 'Tas Kanvas' tinggal 4", time: "1 jam lalu" },
          { id: "n3", title: "Penjualan minggu ini naik 8%", time: "3 jam lalu" },
        ]),
        actionText: "Tambah produk",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Baris KPI Toko",
      props: { columns: "4", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Pendapatan Hari Ini",
          props: {
            title: "Pendapatan Hari Ini",
            value: "Rp 18,4 jt",
            change: "+12%",
            trend: "up",
            subtitle: "dibanding kemarin",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Jumlah Pesanan",
          props: {
            title: "Pesanan",
            value: "342",
            change: "+8%",
            trend: "up",
            subtitle: "hari ini",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Produk Terjual",
          props: {
            title: "Produk Terjual",
            value: "512",
            change: "+5%",
            trend: "up",
            subtitle: "hari ini",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Rata-rata Pesanan",
          props: {
            title: "Rata-rata Pesanan",
            value: "Rp 54.000",
            change: "-2%",
            trend: "down",
            subtitle: "dari minggu lalu",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Grafik dan Tabel Toko",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Grafik dan Pesanan",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "chart-card",
              name: "Grafik Penjualan 30 Hari",
              props: {
                title: "Penjualan 30 Hari",
                subtitle: "Dibanding periode yang sama tahun lalu",
                chartType: "line",
                dataJson: JSON.stringify([
                  { label: "5 Jul", val1: 12, val2: 10 },
                  { label: "8 Jul", val1: 14, val2: 11 },
                  { label: "11 Jul", val1: 13, val2: 12 },
                  { label: "14 Jul", val1: 17, val2: 13 },
                  { label: "17 Jul", val1: 16, val2: 12 },
                  { label: "20 Jul", val1: 19, val2: 14 },
                  { label: "23 Jul", val1: 18, val2: 13 },
                  { label: "26 Jul", val1: 22, val2: 15 },
                  { label: "29 Jul", val1: 20, val2: 14 },
                  { label: "1 Agu", val1: 24, val2: 16 },
                  { label: "4 Agu", val1: 21, val2: 15 },
                  { label: "7 Agu", val1: 23, val2: 16 },
                ]),
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "data-table",
              name: "10 Pesanan Terbaru",
              props: {
                title: "Pesanan Terbaru",
                subtitle: "10 pesanan terakhir yang masuk hari ini",
                rowsJson: JSON.stringify([
                  { id: "ORD-2451", customer: "Rina Puspita", item: "Tas Kanvas 15L", amount: "Rp 189.000", status: "Dikirim", date: "15 Agu 2026" },
                  { id: "ORD-2450", customer: "Fajar Nugroho", item: "Sandal Kulit Senja", amount: "Rp 129.000", status: "Diproses", date: "15 Agu 2026" },
                  { id: "ORD-2449", customer: "Maya Anggraini", item: "Dompet Kulit Kecil", amount: "Rp 99.000", status: "Selesai", date: "14 Agu 2026" },
                  { id: "ORD-2448", customer: "Teguh Santoso", item: "Tas Kanvas 15L", amount: "Rp 189.000", status: "Selesai", date: "14 Agu 2026" },
                  { id: "ORD-2447", customer: "Laras Wijaya", item: "Jaket Denim Loose", amount: "Rp 245.000", status: "Dikirim", date: "13 Agu 2026" },
                  { id: "ORD-2446", customer: "Andi Firmansyah", item: "Tote Kanvas Polos", amount: "Rp 89.000", status: "Batal", date: "13 Agu 2026" },
                  { id: "ORD-2445", customer: "Sari Dewanti", item: "Sandal Kulit Senja", amount: "Rp 129.000", status: "Selesai", date: "12 Agu 2026" },
                  { id: "ORD-2444", customer: "Bagus Kurniawan", item: "Dompet Kulit Kecil", amount: "Rp 99.000", status: "Diproses", date: "12 Agu 2026" },
                  { id: "ORD-2443", customer: "Intan Permata", item: "Tas Kanvas 15L", amount: "Rp 189.000", status: "Selesai", date: "11 Agu 2026" },
                  { id: "ORD-2442", customer: "Raka Prasetyo", item: "Jaket Denim Loose", amount: "Rp 245.000", status: "Selesai", date: "11 Agu 2026" },
                ]),
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Filter dan Aktivitas",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "bar-filter",
              name: "Filter Status Pesanan",
              props: {
                title: "Filter status pesanan",
                filtersJson: [
                  { label: "Semua" },
                  { label: "Baru" },
                  { label: "Diproses" },
                  { label: "Dikirim" },
                  { label: "Selesai" },
                  { label: "Batal" },
                ],
                activeIndex: 0,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "dashboard-activity-list",
              name: "Log Pesanan",
              props: {
                title: "Log Pesanan",
                description: "Perubahan status terakhir dari 10 menit terakhir",
                items: [
                  { id: "act1", initials: "RP", title: "Pesanan ORD-2451 dikirim", description: "Resi JNE JPX7001234567 diinput oleh admin.", time: "2 menit lalu", status: "success" },
                  { id: "act2", initials: "FA", title: "Pesanan ORD-2450 diproses", description: "Menunggu konfirmasi stok warna cokelat.", time: "8 menit lalu", status: "pending" },
                  { id: "act3", initials: "SI", title: "Refund ORD-2446 diajukan", description: "Pembeli memilih pengembalian dana atas alasan salah ukuran.", time: "25 menit lalu", status: "warning" },
                  { id: "act4", initials: "DA", title: "Produk baru dipublikasikan", description: "'Topi Pantai Lipat' tersedia mulai hari ini.", time: "1 jam lalu", status: "success" },
                ],
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "stack-avatar",
              name: "Staf Toko",
              props: {
                avatarsJson: JSON.stringify([
                  { name: "Ayu Lestari" },
                  { name: "Bayu Pratama" },
                  { name: "Citra Dewi" },
                  { name: "Dimas Arya" },
                  { name: "Elsa Putri" },
                ]),
                extraCount: "+6",
                showExtra: true,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "sparkline",
              name: "Penjualan Mingguan",
              props: {
                label: "Penjualan mingguan",
                value: "Rp 118,4 jt",
                trend: "+12%",
                up: true,
                data: "82,91,88,104,99,112,118",
                height: 48,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
      ],
    },
  ];
}
