import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/**
 * Helpdesk dashboard with ticket KPI row, status filter, ticket table,
 * handling log, support team avatars, weekly chart, and shift calendar.
 */
export function createHelpdeskDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Sapa Support",
      props: {
        brandName: "Sapa Support",
        brandTag: "HELPDESK",
        userName: "Gilang Ramadhan",
        userRole: "Level 2 Support",
        linksJson: JSON.stringify([
          { id: "hd-1", label: "Dashboard", url: "/", icon: "layout-dashboard", active: true },
          { id: "hd-2", label: "Tiket", url: "#tiket", icon: "bar-chart-3", active: false },
          { id: "hd-3", label: "Antrian", url: "#antrian", icon: "credit-card", active: false },
          { id: "hd-4", label: "Pengetahuan", url: "#pengetahuan", icon: "users", active: false },
          { id: "hd-5", label: "Laporan", url: "#laporan", icon: "settings", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Helpdesk",
      props: {
        title: "Helpdesk",
        breadcrumb: "Sapa Support / Helpdesk / Dashboard",
        searchPlaceholder: "Cari tiket, pelanggan, atau artikel...",
        showSearch: true,
        showNotifications: true,
        notificationsMode: "panel",
        notificationsJson: JSON.stringify([
          { id: "n1", title: "Tiket TK-2415 menunggu balasan Anda", time: "5 menit lalu" },
          { id: "n2", title: "SLA tiket TK-2410 akan habis 17.00", time: "1 jam lalu" },
          { id: "n3", title: "Artikel 'Cara reset kartu' disetujui", time: "3 jam lalu" },
        ]),
        actionText: "Buat tiket",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Baris KPI Helpdesk",
      props: { columns: "4", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Tiket Terbuka",
          props: {
            title: "Tiket Terbuka",
            value: "23",
            change: "-4",
            trend: "down",
            subtitle: "dibanding kemarin",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Menunggu Balasan",
          props: {
            title: "Menunggu Balasan",
            value: "8",
            change: "+2",
            trend: "up",
            subtitle: "dari tim terkait",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Terjawab Hari Ini",
          props: {
            title: "Terjawab Hari Ini",
            value: "41",
            change: "+9",
            trend: "up",
            subtitle: "rekor minggu ini",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Rata-rata Waktu",
          props: {
            title: "Rata-rata Waktu",
            value: "1j 40m",
            change: "-12m",
            trend: "down",
            subtitle: "dari rata-rata 7 hari",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "bar-filter",
      name: "Filter Status Tiket",
      props: {
        title: "Filter status tiket",
        filtersJson: [
          { label: "Semua" },
          { label: "Baru" },
          { label: "Diproses" },
          { label: "Selesai" },
          { label: "Ditutup" },
        ],
        activeIndex: 0,
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Tiket dan Log",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Tabel Tiket",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "data-table",
              name: "Tiket Masuk",
              props: {
                title: "Tiket Masuk",
                subtitle: "24 tiket aktif per 15 Agustus 2026",
                rowsJson: JSON.stringify([
                  { id: "TK-2415", customer: "Ratna Sari", item: "Kartu ditolak saat belanja online", amount: "Tinggi", status: "Diproses", date: "15 Agu 2026" },
                  { id: "TK-2414", customer: "Hendra Gunawan", item: "Tagihan double potong", amount: "Tinggi", status: "Baru", date: "15 Agu 2026" },
                  { id: "TK-2413", customer: "Sari Permata", item: "Cara ganti nomor ponsel", amount: "Sedang", status: "Selesai", date: "14 Agu 2026" },
                  { id: "TK-2412", customer: "Yusuf Hidayat", item: "Limit kartu tidak muncul", amount: "Sedang", status: "Diproses", date: "14 Agu 2026" },
                  { id: "TK-2411", customer: "Mega Safitri", item: "E-statement tidak terkirim", amount: "Rendah", status: "Selesai", date: "13 Agu 2026" },
                  { id: "TK-2410", customer: "Bagas Wibowo", item: "Penutupan kartu hilang", amount: "Tinggi", status: "Diproses", date: "13 Agu 2026" },
                  { id: "TK-2409", customer: "Lina Marlina", item: "Pertanyaan promo agustus", amount: "Rendah", status: "Selesai", date: "12 Agu 2026" },
                  { id: "TK-2408", customer: "Rizky Ananda", item: "ATM tertahan", amount: "Tinggi", status: "Selesai", date: "12 Agu 2026" },
                ]),
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "pagination",
              name: "Paginasi Tiket",
              props: {
                currentPage: 1,
                totalPages: 6,
                showPrevNext: true,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Log dan Tim",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "dashboard-activity-list",
              name: "Log Penanganan",
              props: {
                title: "Log Penanganan",
                description: "Tindakan tim support dalam 2 jam terakhir",
                items: [
                  { id: "act1", initials: "GR", title: "Gilang menjawab TK-2415", description: "Meneruskan ke tim fraud untuk pengecekan transaksi.", time: "10 menit lalu", status: "success" },
                  { id: "act2", initials: "NM", title: "Nadia mengangkat TK-2410", description: "Proses penggantian kartu dimulai via kurir.", time: "40 menit lalu", status: "pending" },
                  { id: "act3", initials: "FK", title: "Fikri eskalasi TK-2414", description: "Potongan ganda dikonfirmasi, refund dijadwalkan.", time: "1 jam lalu", status: "warning" },
                  { id: "act4", initials: "AD", title: "Artikel KB diperbarui", description: "'Cara cetak e-statement' direvisi dan diterbitkan.", time: "2 jam lalu", status: "success" },
                ],
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "stack-avatar",
              name: "Tim Support",
              props: {
                avatarsJson: JSON.stringify([
                  { name: "Gilang Ramadhan" },
                  { name: "Nadia Mutiara" },
                  { name: "Fikri Kurnia" },
                  { name: "Aditya Putra" },
                  { name: "Salsa Aulia" },
                ]),
                extraCount: "+3",
                showExtra: true,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "form-add-data",
              name: "Form Tiket Baru",
              props: {
                title: "Tiket Baru",
                description: "Lengkapi detail tiket dari pelanggan.",
                fieldsJson: JSON.stringify([
                  { label: "Nama pelanggan", placeholder: "Nama lengkap", type: "text" },
                  { label: "Subjek", placeholder: "Ringkasan masalah", type: "text" },
                  { label: "Prioritas", placeholder: "Tinggi / Sedang / Rendah", type: "text" },
                  { label: "Tanggal masuk", placeholder: "2026-08-15", type: "date" },
                ]),
                submitText: "Buat tiket",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Grafik dan Jadwal",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "chart-card",
          name: "Grafik Tiket per Minggu",
          props: {
            title: "Tiket per Minggu",
            subtitle: "Tiket masuk, 4 minggu terakhir",
            chartType: "bar",
            dataJson: JSON.stringify([
              { label: "Minggu 1", val1: 64, val2: 52 },
              { label: "Minggu 2", val1: 71, val2: 58 },
              { label: "Minggu 3", val1: 68, val2: 63 },
              { label: "Minggu 4", val1: 82, val2: 61 },
            ]),
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "calendar-widget",
          name: "Jadwal Shift",
          props: {
            monthLabel: "Agustus 2026",
            daysJson: [2, 6, 9, 13, 16, 20, 23, 27],
            todayDay: 15,
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
  ];
}
