import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/**
 * Personal finance dashboard with balance KPI row, cash-flow chart,
 * transaction table, budget progress bars, spending sparkline, and
 * a due-date calendar with a transaction entry form.
 */
export function createKeuanganDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Nura Keuangan",
      props: {
        brandName: "Nura",
        brandTag: "FINANSIAL",
        userName: "Rina Maharani",
        userRole: "Pemilik akun",
        linksJson: JSON.stringify([
          { id: "keu-1", label: "Ringkasan", url: "/", icon: "layout-dashboard", active: true },
          { id: "keu-2", label: "Transaksi", url: "#transaksi", icon: "credit-card", active: false },
          { id: "keu-3", label: "Anggaran", url: "#anggaran", icon: "bar-chart-3", active: false },
          { id: "keu-4", label: "Kartu", url: "#kartu", icon: "settings", active: false },
          { id: "keu-5", label: "Laporan", url: "#laporan", icon: "users", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Keuangan",
      props: {
        title: "Keuangan",
        breadcrumb: "Nura / Ringkasan Keuangan",
        searchPlaceholder: "Cari transaksi atau kategori...",
        showSearch: true,
        showNotifications: true,
        notificationsMode: "modal",
        notificationsJson: JSON.stringify([
          { id: "n1", title: "Tagihan PLN jatuh tempo besok", time: "3 jam lalu" },
          { id: "n2", title: "Cicilan KPR terpotong otomatis", time: "Hari ini, 06.00" },
          { id: "n3", title: "Budget 'Makan' tersisa 20%", time: "Kemarin" },
        ]),
        actionText: "Tambah transaksi",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Baris KPI Keuangan",
      props: { columns: "4", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Saldo",
          props: {
            title: "Saldo",
            value: "Rp 48,6 jt",
            change: "+4,2%",
            trend: "up",
            subtitle: "semua rekening",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Pemasukan Bulan Ini",
          props: {
            title: "Pemasukan Bulan Ini",
            value: "Rp 12,3 jt",
            change: "+8%",
            trend: "up",
            subtitle: "dibanding Juli 2026",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Pengeluaran",
          props: {
            title: "Pengeluaran",
            value: "Rp 8,9 jt",
            change: "+3%",
            trend: "up",
            subtitle: "dibanding Juli 2026",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Cicilan Jatuh Tempo",
          props: {
            title: "Cicilan Jatuh Tempo",
            value: "2",
            change: "+1",
            trend: "up",
            subtitle: "dalam 7 hari ke depan",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Grafik dan Form",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "chart-card",
          name: "Grafik Arus Kas",
          props: {
            title: "Arus Kas 6 Bulan",
            subtitle: "Pemasukan vs pengeluaran per bulan",
            chartType: "line",
            dataJson: JSON.stringify([
              { label: "Mar", val1: 9.5, val2: 8.1 },
              { label: "Apr", val1: 11.2, val2: 8.8 },
              { label: "Mei", val1: 10.8, val2: 9.4 },
              { label: "Jun", val1: 12.1, val2: 9.9 },
              { label: "Jul", val1: 11.4, val2: 8.6 },
              { label: "Agu", val1: 12.3, val2: 8.9 },
            ]),
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "form-add-data",
          name: "Form Tambah Transaksi",
          props: {
            title: "Tambah Transaksi",
            description: "Catat pengeluaran atau pemasukan baru.",
            fieldsJson: JSON.stringify([
              { label: "Keterangan", placeholder: "Misal: Belanja bulanan", type: "text" },
              { label: "Kategori", placeholder: "Kebutuhan rumah", type: "text" },
              { label: "Jumlah", placeholder: "Rp", type: "number" },
              { label: "Tanggal", placeholder: "2026-08-15", type: "date" },
            ]),
            submitText: "Simpan transaksi",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Transaksi dan Anggaran",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Tabel Transaksi",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "data-table",
              name: "Transaksi Terakhir",
              props: {
                title: "Transaksi Terakhir",
                subtitle: "10 transaksi tercatat terbaru",
                rowsJson: JSON.stringify([
                  { id: "TRX-2148", customer: "Alfamart Cikutra", item: "Kebutuhan rumah", amount: "Rp 156.500", status: "Tercatat", date: "15 Agu 2026" },
                  { id: "TRX-2147", customer: "Gaji bulanan", item: "Pemasukan", amount: "Rp 9.750.000", status: "Tercatat", date: "1 Agu 2026" },
                  { id: "TRX-2146", customer: "PLN Pasca Bayar", item: "Listrik", amount: "Rp 482.000", status: "Terjadwal", date: "15 Agu 2026" },
                  { id: "TRX-2145", customer: "Indomaret Dago", item: "Makan & minum", amount: "Rp 68.400", status: "Tercatat", date: "14 Agu 2026" },
                  { id: "TRX-2144", customer: "Bensin Pertamina", item: "Transportasi", amount: "Rp 100.000", status: "Tercatat", date: "14 Agu 2026" },
                  { id: "TRX-2143", customer: "Cicilan KPR", item: "Perumahan", amount: "Rp 3.200.000", status: "Otomatis", date: "12 Agu 2026" },
                  { id: "TRX-2142", customer: "Transmart Antapani", item: "Belanja bulanan", amount: "Rp 1.240.000", status: "Tercatat", date: "10 Agu 2026" },
                  { id: "TRX-2141", customer: "Jajan anak sekolah", item: "Pendidikan", amount: "Rp 150.000", status: "Tercatat", date: "9 Agu 2026" },
                  { id: "TRX-2140", customer: "Netflix", item: "Langganan", amount: "Rp 149.000", status: "Otomatis", date: "8 Agu 2026" },
                  { id: "TRX-2139", customer: "Gojek", item: "Transportasi", amount: "Rp 42.000", status: "Tercatat", date: "8 Agu 2026" },
                ]),
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "pagination",
              name: "Paginasi Transaksi",
              props: {
                currentPage: 1,
                totalPages: 5,
                showPrevNext: true,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Anggaran",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "section-basic",
              name: "Judul Anggaran Tersisa",
              props: {
                heading: "Anggaran Tersisa",
                paragraph: "Sisa budget kategori per 15 Agustus 2026.",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Makan",
              props: {
                label: "Makan",
                value: 62,
                showValue: true,
                variant: "warning",
                hint: "Tersisa Rp 1,24 jt dari Rp 2 jt",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Transport",
              props: {
                label: "Transport",
                value: 45,
                showValue: true,
                variant: "primary",
                hint: "Tersisa Rp 405 rb dari Rp 900 rb",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Hiburan",
              props: {
                label: "Hiburan",
                value: 80,
                showValue: true,
                variant: "danger",
                hint: "Tersisa Rp 120 rb dari Rp 600 rb",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "sparkline",
              name: "Pengeluaran 7 Hari",
              props: {
                label: "Pengeluaran 7 hari",
                value: "Rp 2,1 jt",
                trend: "+6%",
                up: false,
                data: "240,310,275,420,330,385,415",
                height: 48,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "calendar-widget",
              name: "Jatuh Tempo Tagihan",
              props: {
                monthLabel: "Agustus 2026",
                daysJson: [3, 8, 12, 17, 21, 25],
                todayDay: 15,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
      ],
    },
  ];
}
