import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/** Dashboard operasional modern — terinspirasi dari template "shadcn-admin". */
export function createOperasionalDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "sidebar-icon",
      name: "Sidebar Icon Operasional",
      props: {
        logoText: "G",
        workspaceLabel: "Garuda Ops",
        statusLabel: "Semua sistem normal",
        defaultOpen: true,
        links: [
          { icon: "layout-dashboard", label: "Ringkasan", url: "#" },
          { icon: "users", label: "Tim", url: "#" },
          { icon: "calendar", label: "Jadwal", url: "#" },
          { icon: "bar-chart-3", label: "Analitik", url: "#" },
          { icon: "settings", label: "Pengaturan", url: "#" },
        ],
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Operasional",
      props: {
        title: "Operasional Hari Ini",
        breadcrumb: "Beranda / Operasional",
        searchPlaceholder: "Cari tim, jadwal, atau laporan...",
        actionText: "+ Laporkan",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "breadcrumb",
      name: "Breadcrumb Operasional",
      props: {
        homeUrl: "#",
        separator: "slanted",
        showHome: true,
        itemsJson: JSON.stringify([
          { label: "Beranda", url: "#" },
          { label: "Operasional", url: "#" },
          { label: "Hari Ini", url: "#" },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Shift Aktif",
      props: {
        title: "Shift Aktif",
        value: "38",
        change: "+4",
        trend: "up",
        subtitle: "dari 3 lokasi cabang",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Kehadiran",
      props: {
        title: "Kehadiran",
        value: "96,4%",
        change: "+1,2%",
        trend: "up",
        subtitle: "rata-rata minggu ini",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Jam Kerja",
      props: {
        title: "Jam Kerja",
        value: "412",
        change: "+38",
        trend: "up",
        subtitle: "jam tercatat hari ini",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "kpi-card",
      name: "KPI Insiden",
      props: {
        title: "Insiden",
        value: "3",
        change: "-2",
        trend: "down",
        subtitle: "insiden belum selesai",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Beban Harian",
      props: {
        title: "Beban Kerja Harian",
        chartType: "bar",
        dataJson: JSON.stringify([
          { month: "Sen", revenue: 320 },
          { month: "Sel", revenue: 415 },
          { month: "Rab", revenue: 388 },
          { month: "Kam", revenue: 452 },
          { month: "Jum", revenue: 396 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "chart-card",
      name: "Grafik Distribusi Tim",
      props: {
        title: "Distribusi Tim",
        chartType: "donut",
        dataJson: JSON.stringify([
          { label: "Produksi", value: 34 },
          { label: "Lapangan", value: 27 },
          { label: "Admin", value: 18 },
          { label: "Pemeliharaan", value: 21 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-activity-list",
      name: "Log Operasional",
      props: {
        title: "Log Operasional",
        description: "Peristiwa penting yang tercatat hari ini",
        items: [
          { initials: "PL", title: "Shift pagi dimulai", description: "38 pekerja masuk tepat waktu di 3 cabang.", time: "06.00", status: "selesai" },
          { initials: "KD", title: "Insiden jaringan dilaporkan", description: "Gangguan internet di gudang C, sedang ditangani.", time: "09.12", status: "proses" },
          { initials: "NT", title: "Laporan harian diunggah", description: "Laporan produksi cabang Jogja tersedia.", time: "11.40", status: "selesai" },
          { initials: "AR", title: "Jadwal lembur disetujui", description: "Lembur 8 orang untuk pesanan akhir bulan.", time: "13.05", status: "proses" },
          { initials: "MS", title: "Inventaris diperbarui", description: "Stok perlengkapan gudang A dihitung ulang.", time: "15.30", status: "selesai" },
        ],
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "calendar-widget",
      name: "Kalender Jadwal",
      props: {
        monthLabel: "Agustus 2026",
        todayDay: 20,
        daysJson: JSON.stringify([
          { day: 18 },
          { day: 19 },
          { day: 20 },
          { day: 21 },
          { day: 22 },
          { day: 25 },
          { day: 28 },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "progress-bar",
      name: "Progres Target Bulanan",
      props: {
        label: "Target produksi bulan ini",
        value: 74,
        showValue: true,
        variant: "primary",
        hint: "74% tercapai — 7 hari tersisa",
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "stack-avatar",
      name: "Tim yang Sedang Aktif",
      props: {
        avatarsJson: JSON.stringify([
          { name: "Putri Lestari" },
          { name: "Bayu Firmansyah" },
          { name: "Citra Ayu" },
          { name: "Dodi Kurniawan" },
          { name: "Eka Putra" },
        ]),
        extraCount: "+12",
        showExtra: true,
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "data-table",
      name: "Rekap Kehadiran",
      props: {
        title: "Rekap Kehadiran Hari Ini",
        subtitle: "Status kehadiran tim produksi dan lapangan",
        rowsJson: JSON.stringify([
          { id: "EMP-102", customer: "Putri Lestari", item: "Produksi A", amount: "8 jam", status: "Hadir", date: "20 Agu 2026" },
          { id: "EMP-107", customer: "Bayu Firmansyah", item: "Lapangan", amount: "7,5 jam", status: "Hadir", date: "20 Agu 2026" },
          { id: "EMP-113", customer: "Citra Ayu", item: "Admin", amount: "8 jam", status: "Hadir", date: "20 Agu 2026" },
          { id: "EMP-118", customer: "Dodi Kurniawan", item: "Produksi B", amount: "0 jam", status: "Izin", date: "20 Agu 2026" },
          { id: "EMP-121", customer: "Eka Putra", item: "Pemeliharaan", amount: "8 jam", status: "Hadir", date: "20 Agu 2026" },
        ]),
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "pagination",
      name: "Navigasi Halaman Tabel",
      props: {
        currentPage: 2,
        totalPages: 5,
        showPrevNext: true,
      },
      styles: { isDashboardWidget: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
  ];
}