import type { RawTemplateNode } from "@/templates";
import { uid } from "@/lib/utils";

/**
 * Project portfolio dashboard with KPI row, progress bars, workload chart,
 * task table, deadline calendar, and team avatars.
 */
export function createProjectDashboardNodes(): RawTemplateNode[] {
  return [
    {
      id: uid(),
      componentType: "app-sidebar",
      name: "Navigasi Garasi Karya",
      props: {
        brandName: "Garasi Karya",
        brandTag: "PROYEK",
        userName: "Andi Maulana",
        userRole: "Project Manager",
        linksJson: JSON.stringify([
          { id: "prj-1", label: "Ringkasan", url: "/", icon: "layout-dashboard", active: true },
          { id: "prj-2", label: "Proyek", url: "#proyek", icon: "bar-chart-3", active: false },
          { id: "prj-3", label: "Tugas", url: "#tugas", icon: "credit-card", active: false },
          { id: "prj-4", label: "Tim", url: "#tim", icon: "users", active: false },
          { id: "prj-5", label: "Risiko", url: "#risiko", icon: "settings", active: false },
        ]),
      },
      styles: { isDashboardSidebar: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "dashboard-header",
      name: "Header Portofolio Proyek",
      props: {
        title: "Portofolio Proyek",
        breadcrumb: "Garasi Karya / Proyek / Ringkasan",
        searchPlaceholder: "Cari proyek, tugas, atau anggota...",
        showSearch: true,
        showNotifications: true,
        notificationsMode: "panel",
        notificationsJson: JSON.stringify([
          { id: "n1", title: "Deadline 'Aplikasi Kasir' 3 hari lagi", time: "1 jam lalu" },
          { id: "n2", title: "Rizky menandai tugas QA selesai", time: "4 jam lalu" },
          { id: "n3", title: "Anggaran 'Migrasi Server' tersisa 18%", time: "Kemarin" },
        ]),
        actionText: "Buat proyek",
      },
      styles: { isDashboardHeader: "true" },
      tabletOverride: {},
      mobileOverride: {},
      metadata: { isDashboardComponent: true },
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Baris KPI Proyek",
      props: { columns: "4", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Proyek Aktif",
          props: {
            title: "Proyek Aktif",
            value: "12",
            change: "+2",
            trend: "up",
            subtitle: "dari bulan lalu",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Proyek Selesai",
          props: {
            title: "Selesai Bulan Ini",
            value: "4",
            change: "+1",
            trend: "up",
            subtitle: "dari Juli 2026",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Tugas Terbuka",
          props: {
            title: "Tugas Terbuka",
            value: "37",
            change: "-5",
            trend: "down",
            subtitle: "dari minggu lalu",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "kpi-card",
          name: "KPI Anggaran Terpakai",
          props: {
            title: "Anggaran Terpakai",
            value: "Rp 1,2 M",
            change: "+9%",
            trend: "up",
            subtitle: "dari total Rp 2,8 M",
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Progress dan Aktivitas",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Progress Proyek",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "section-basic",
              name: "Judul Progress Proyek",
              props: {
                heading: "Progress Proyek",
                paragraph: "Persentase penyelesaian dari tiga proyek yang sedang berjalan.",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Aplikasi Kasir",
              props: {
                label: "Aplikasi Kasir",
                value: 78,
                showValue: true,
                variant: "success",
                hint: "Menuju UAT minggu depan",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Website UMKM",
              props: {
                label: "Website UMKM",
                value: 54,
                showValue: true,
                variant: "primary",
                hint: "Tahap konten dan aset",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "progress-bar",
              name: "Progress Migrasi Server",
              props: {
                label: "Migrasi Server",
                value: 32,
                showValue: true,
                variant: "warning",
                hint: "Menunggu data lama dari vendor",
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
        {
          id: uid(),
          componentType: "dashboard-activity-list",
          name: "Aktivitas Proyek",
          props: {
            title: "Aktivitas Proyek",
            description: "Perkembangan terakhir di seluruh portofolio",
            items: [
              { id: "act1", initials: "AM", title: "Andi menandai milestone UAT", description: "'Aplikasi Kasir' siap uji terima pengguna minggu depan.", time: "30 menit lalu", status: "success" },
              { id: "act2", initials: "RS", title: "Rizky mengunggah aset website", description: "17 gambar produk UMKM masuk ke staging.", time: "2 jam lalu", status: "success" },
              { id: "act3", initials: "DN", title: "Dina mengajukan tambahan anggaran", description: "Rp 45 juta untuk lisensi server tahap kedua.", time: "5 jam lalu", status: "warning" },
              { id: "act4", initials: "PS", title: "Pandu menunggu konfirmasi vendor", description: "Data lama belum keluar dari penyedia hosting.", time: "Kemarin", status: "pending" },
            ],
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Grafik dan Tugas",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "chart-card",
          name: "Grafik Beban Kerja",
          props: {
            title: "Beban Kerja per Anggota",
            subtitle: "Tugas aktif dan selesai per orang, Agustus 2026",
            chartType: "bar",
            dataJson: JSON.stringify([
              { label: "Andi", val1: 6, val2: 3 },
              { label: "Rizky", val1: 8, val2: 5 },
              { label: "Dina", val1: 5, val2: 2 },
              { label: "Pandu", val1: 7, val2: 4 },
              { label: "Salsa", val1: 3, val2: 1 },
            ]),
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "grid-container",
          name: "Kolom Tabel Tugas",
          props: { columns: "1", gap: "md" },
          children: [
            {
              id: uid(),
              componentType: "data-table",
              name: "Daftar Tugas",
              props: {
                title: "Daftar Tugas",
                subtitle: "Tugas terbuka per 15 Agustus 2026",
                rowsJson: JSON.stringify([
                  { id: "TGS-041", customer: "Salsa Puspita", item: "Desain UI halaman transaksi", amount: "16 jam", status: "Diproses", date: "18 Agu 2026" },
                  { id: "TGS-040", customer: "Rizky Saputra", item: "Konten katalog UMKM", amount: "8 jam", status: "Selesai", date: "15 Agu 2026" },
                  { id: "TGS-039", customer: "Dina Nuraini", item: "Skema backup server", amount: "24 jam", status: "Diproses", date: "21 Agu 2026" },
                  { id: "TGS-038", customer: "Pandu Setiawan", item: "Migrasi data pelanggan", amount: "32 jam", status: "Menunggu", date: "25 Agu 2026" },
                  { id: "TGS-037", customer: "Andi Maulana", item: "Persiapan UAT kasir", amount: "6 jam", status: "Selesai", date: "14 Agu 2026" },
                  { id: "TGS-036", customer: "Salsa Puspita", item: "Prototipe halaman laporan", amount: "12 jam", status: "Diproses", date: "20 Agu 2026" },
                ]),
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
            {
              id: uid(),
              componentType: "pagination",
              name: "Paginasi Tugas",
              props: {
                currentPage: 1,
                totalPages: 5,
                showPrevNext: true,
              },
              styles: { isDashboardWidget: "true" },
              tabletOverride: {},
              mobileOverride: {},
              metadata: { isDashboardComponent: true },
            },
          ],
        },
      ],
    },
    {
      id: uid(),
      componentType: "grid-container",
      name: "Kalender dan Tim",
      props: { columns: "2", gap: "md" },
      children: [
        {
          id: uid(),
          componentType: "calendar-widget",
          name: "Kalender Deadline",
          props: {
            monthLabel: "Agustus 2026",
            daysJson: [5, 8, 12, 15, 18, 21, 25],
            todayDay: 15,
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
        {
          id: uid(),
          componentType: "stack-avatar",
          name: "Tim Inti",
          props: {
            avatarsJson: JSON.stringify([
              { name: "Andi Maulana" },
              { name: "Salsa Puspita" },
              { name: "Rizky Saputra" },
              { name: "Dina Nuraini" },
              { name: "Pandu Setiawan" },
            ]),
            extraCount: "+7",
            showExtra: true,
          },
          styles: { isDashboardWidget: "true" },
          tabletOverride: {},
          mobileOverride: {},
          metadata: { isDashboardComponent: true },
        },
      ],
    },
  ];
}
