import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString } from "@/lib/registry/shared";
import { listValue, nodeList, uniqueId } from "../_shared/content";

interface Testimonial { id: string; quote: string; name: string; role: string; initials: string; }
const FALLBACK: Testimonial[] = [
  { id: "nadia", quote: "Prosesnya terasa jernih sejak awal. Tim kami akhirnya punya bahasa yang sama untuk menjelaskan arah brand.", name: "Nadia Kurnia", role: "Founder, Rona Studio", initials: "NK" },
  { id: "rangga", quote: "Bukan hanya terlihat lebih baik—website ini membuat calon klien jauh lebih cepat memahami apa yang kami tawarkan.", name: "Rangga Pratama", role: "Direktur, Karsa", initials: "RP" },
  { id: "salsa", quote: "Kami suka karena semuanya terasa sangat manusiawi: rapi, tidak berlebihan, dan mudah diteruskan oleh tim internal.", name: "Salsa Mutiara", role: "Marketing Lead, Foli", initials: "SM" },
];
function testimonials(node: Node): Testimonial[] { const list = nodeList(node, "items").map((item, index) => { const quote = listValue(item, "quote"); if (!quote) return null; const name = listValue(item, "name", "Pelanggan"); return { id: uniqueId("quote", index, name), quote, name, role: listValue(item, "role"), initials: listValue(item, "initials", name.slice(0, 2).toUpperCase()) }; }).filter((item): item is Testimonial => item !== null); return list.length ? list : FALLBACK; }

export function testimonialGridExport(node: Node): ExportResult {
  const eyebrow = propString(node, "eyebrow").trim() || "Cerita dari mereka";
  const title = propString(node, "title").trim() || "Keputusan kecil yang membuat pekerjaan terasa lebih ringan.";
  const description = propString(node, "description").trim() || "Dengar langsung dari orang-orang yang menjalankan bisnisnya setiap hari.";
  const requested = propString(node, "columns"); const cols = requested === "1" || requested === "2" || requested === "3" ? requested : "3";
  const cards = testimonials(node).map((item, index) => `<article class="bi-testimonial${index === 1 ? " bi-testimonial-offset" : ""}"><span class="bi-testimonial-mark" aria-hidden="true">“</span><blockquote>“${escapeHtml(item.quote)}”</blockquote><footer><span class="bi-avatar">${escapeHtml(item.initials)}</span><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.role)}</small></span></footer></article>`).join("");
  return { html: `<section class="bi-testimonials"><div class="bi-container"><header class="bi-testimonials-head"><p>${escapeHtml(eyebrow)}</p><h2 class="bi-title">${escapeHtml(title)}</h2><span>${escapeHtml(description)}</span></header><div class="bi-testimonials-grid cols-${cols}">${cards}</div></div></section>`, css: `.bi-testimonials { padding-block: clamp(3.5rem, 8vw, 6.5rem); background: color-mix(in srgb, var(--bi-secondary) 30%, var(--bi-bg)); color: var(--bi-fg); }.bi-testimonials-head { max-width: 42rem; margin: 0 auto; text-align: center; }.bi-testimonials-head > p { margin: 0; color: var(--bi-primary); font-size: .68rem; font-weight: 800; letter-spacing: .14em; text-transform: uppercase; }.bi-testimonials-head h2 { margin: .75rem 0 0; }.bi-testimonials-head > span { display: block; margin-top: 1rem; color: var(--bi-muted-fg); font-size: .95rem; line-height: 1.7; }.bi-testimonials-grid { display: grid; gap: 1rem; margin-top: 2.5rem; }.bi-testimonials-grid.cols-1 { grid-template-columns: 1fr; }.bi-testimonials-grid.cols-2 { grid-template-columns: repeat(2,minmax(0,1fr)); }.bi-testimonials-grid.cols-3 { grid-template-columns: repeat(3,minmax(0,1fr)); }.bi-testimonial { min-width: 0; padding: 1.4rem; border: 1px solid var(--bi-border); border-radius: var(--bi-radius); background: var(--bi-card); box-shadow: 0 1px 2px rgba(0,0,0,.04); }.bi-testimonial-mark { color: color-mix(in srgb, var(--bi-primary) 55%, transparent); font: 800 2.25rem/.7 Georgia,serif; }.bi-testimonial blockquote { margin: 1rem 0 0; font-size: .96rem; font-weight: 600; line-height: 1.75; letter-spacing: -.01em; }.bi-testimonial footer { display: flex; align-items: center; gap: .75rem; margin-top: 1.5rem; padding-top: 1rem; border-top: 1px solid var(--bi-border); }.bi-avatar { display: grid; width: 2.25rem; height: 2.25rem; place-items: center; border-radius: 50%; background: var(--bi-primary); color: var(--bi-primary-fg); font-size: .65rem; font-weight: 800; }.bi-testimonial footer strong,.bi-testimonial footer small { display: block; }.bi-testimonial footer strong { font-size: .85rem; }.bi-testimonial footer small { margin-top: .2rem; color: var(--bi-muted-fg); font-size: .72rem; } @media (min-width: 761px) { .bi-testimonials-grid.cols-3 .bi-testimonial-offset { transform: translateY(1.25rem); } } @media (max-width:760px) { .bi-testimonials-grid { grid-template-columns: 1fr !important; } }` };
}
