import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString, sanitizeUrl } from "@/lib/registry/shared";
import { directNavigationLinks, navInstanceId } from "../_shared/navigation";

export function navbarGlassExport(node: Node): ExportResult {
  const logo = propString(node, "logoText").trim() || "Nawala";
  const cta = propString(node, "ctaText").trim() || "Mari bicara";
  const ctaUrl = sanitizeUrl(propString(node, "ctaUrl").trim() || "#kontak");
  const instance = navInstanceId(node, "glass-nav");
  const menuId = `${instance}-menu`;
  const links = directNavigationLinks(node, 3);
  const linksHtml = links.map((link) => `<a href="${escapeHtml(link.url)}" class="bi-glass-link">${escapeHtml(link.label)}</a>`).join("");

  return {
    html: `<header class="bi-glass-wrap"><nav class="bi-glass-nav" data-bi-glass-nav="${instance}" data-open="false" aria-label="Navigasi utama"><a class="bi-glass-brand" href="#"><span aria-hidden="true">N</span>${escapeHtml(logo)}</a><div class="bi-glass-links">${linksHtml}</div><a class="bi-glass-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">↗</span></a><button class="bi-glass-toggle" type="button" data-bi-glass-toggle aria-label="Buka menu" aria-expanded="false" aria-controls="${menuId}"><i></i><i></i></button><div class="bi-glass-mobile" id="${menuId}">${linksHtml}<a class="bi-glass-mobile-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">↗</span></a></div></nav></header>`,
    css: `.bi-glass-wrap{position:relative;z-index:20;padding:.75rem;isolation:isolate}.bi-glass-nav{position:relative;display:flex;max-width:72rem;align-items:center;justify-content:space-between;gap:.75rem;margin:auto;padding:.5rem .75rem;border:1px solid color-mix(in srgb,var(--bi-border) 82%,transparent);border-radius:999px;background:color-mix(in srgb,var(--bi-card) 75%,transparent);box-shadow:0 10px 28px color-mix(in srgb,var(--bi-fg) 8%,transparent);backdrop-filter:blur(18px);color:var(--bi-fg);font-family:var(--bi-font-body)}.bi-glass-brand{display:flex;min-width:0;align-items:center;gap:.55rem;padding:.35rem .5rem;color:var(--bi-fg);font-family:var(--bi-font-heading);font-size:1rem;font-weight:800;letter-spacing:-.04em;text-decoration:none}.bi-glass-brand span{display:grid;width:1.5rem;height:1.5rem;place-items:center;border-radius:50%;background:var(--bi-primary);color:var(--bi-primary-fg);font:900 .62rem/1 var(--bi-font-body)}.bi-glass-links{display:flex;align-items:center;gap:.1rem}.bi-glass-link{position:relative;padding:.55rem .75rem;border-radius:999px;color:var(--bi-muted-fg);font-size:.86rem;font-weight:650;text-decoration:none;transition:color .2s ease,background .2s ease,transform .2s ease}.bi-glass-link:hover{background:color-mix(in srgb,var(--bi-bg) 80%,transparent);color:var(--bi-fg);transform:translateY(-1px)}.bi-glass-cta,.bi-glass-mobile-cta{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;padding:.7rem 1rem;border-radius:999px;background:var(--bi-fg);color:var(--bi-bg);font-size:.76rem;font-weight:800;text-decoration:none;transition:transform .2s ease}.bi-glass-cta:hover,.bi-glass-mobile-cta:hover{transform:translateY(-2px)}.bi-glass-toggle{display:none;width:2.25rem;height:2.25rem;place-content:center;gap:.28rem;border:1px solid var(--bi-border);border-radius:50%;background:var(--bi-bg);color:var(--bi-fg);cursor:pointer}.bi-glass-toggle i{display:block;width:.95rem;height:1.5px;border-radius:2px;background:currentColor;transition:transform .22s ease}.bi-glass-mobile{display:none}@media(max-width:720px){.bi-glass-wrap{padding:.7rem}.bi-glass-links,.bi-glass-cta{display:none}.bi-glass-toggle{display:grid}.bi-glass-nav[data-open="true"] .bi-glass-toggle i:first-child{transform:translateY(2.3px) rotate(45deg)}.bi-glass-nav[data-open="true"] .bi-glass-toggle i:last-child{transform:translateY(-2.3px) rotate(-45deg)}.bi-glass-nav[data-open="true"] .bi-glass-mobile{position:absolute;top:calc(100% + .6rem);right:0;left:0;display:grid;gap:.15rem;padding:.5rem;border:1px solid var(--bi-border);border-radius:var(--bi-radius);background:var(--bi-card);box-shadow:var(--bi-shadow)}.bi-glass-mobile .bi-glass-link{padding:.72rem .75rem;border-radius:calc(var(--bi-radius) * .75)}.bi-glass-mobile-cta{margin-top:.25rem;border-radius:calc(var(--bi-radius) * .75);padding:.78rem 1rem;background:var(--bi-primary);color:var(--bi-primary-fg)}}`,
    js: `document.querySelectorAll('[data-bi-glass-nav="${instance}"]').forEach(function(nav){var button=nav.querySelector('[data-bi-glass-toggle]');if(!button)return;button.addEventListener('click',function(){var open=nav.dataset.open==='true';nav.dataset.open=String(!open);button.setAttribute('aria-expanded',String(!open));button.setAttribute('aria-label',open?'Buka menu':'Tutup menu');});nav.querySelectorAll('.bi-glass-mobile a').forEach(function(link){link.addEventListener('click',function(){nav.dataset.open='false';button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Buka menu');});});});`,
  };
}
