"use client";

import { ChevronDown } from "lucide-react";
import type { Node, Theme } from "@/lib/schema/types";
import { resolveTheme } from "@/lib/theme/presets";
import { projectTokenStyle, propString, themeTokenStyle } from "@/lib/registry/shared";
import { InlineEditableText } from "@/components/preview/InlineEditable";
import { listValue, nodeList, uniqueId } from "../_shared/content";
import { useRepeaterEditor } from "../_shared/inline";
import { usePreviewDevice } from "@/components/preview/PreviewDeviceContext";

interface Faq { id: string; question: string; answer: string; }
const FALLBACK: Faq[] = [
  { id:"duration",question:"Berapa lama proses pembuatan website?",answer:"Ruang lingkup sederhana biasanya dapat selesai dalam 2–4 minggu. Kami menyepakati jadwal yang jelas sebelum pekerjaan dimulai." }, { id:"edit",question:"Apakah saya bisa mengubah isi setelah website selesai?",answer:"Bisa. Anda dapat mengubah teks, gambar, tautan, warna, dan susunan bagian langsung dari builder tanpa menulis kode." }, { id:"mobile",question:"Apakah website ini nyaman dibuka dari ponsel?",answer:"Ya. Setiap bagian sudah dirancang responsif, lalu dapat diperiksa kembali melalui mode desktop, tablet, dan ponsel di kanvas." }, { id:"grow",question:"Bagaimana jika kebutuhan saya bertambah?",answer:"Mulai dari struktur yang paling penting terlebih dahulu. Bagian baru dapat ditambahkan kapan saja saat bisnis Anda tumbuh." },
];
function items(node:Node):Faq[]{const list=nodeList(node,"items").map((item,index)=>{const question=listValue(item,"question");const answer=listValue(item,"answer");if(!question||!answer)return null;return{id:uniqueId("faq",index,question),question,answer};}).filter((item):item is Faq=>item!==null);return list.length?list:FALLBACK;}
export function FaqAccordionPreview({node,theme}:{node:Node;theme:Theme}){const tokens=resolveTheme(theme);const device=usePreviewDevice();const {setValue}=useRepeaterEditor(node,"items");const eyebrow=propString(node,"eyebrow").trim()||"Pertanyaan yang sering muncul";const title=propString(node,"title").trim()||"Semua yang perlu Anda tahu sebelum mulai.";const description=propString(node,"description").trim()||"Jika jawabannya belum ada di sini, Anda selalu bisa menghubungi kami untuk berdiskusi.";const padding=device==="mobile"?"px-5 py-12":device?"px-8 py-20":"px-5 py-12 sm:px-8 sm:py-20";const layout=device==="mobile"?"grid-cols-1 gap-8":device?"grid-cols-[.8fr_1.2fr] gap-16":"grid-cols-1 gap-8 lg:grid-cols-[.8fr_1.2fr] lg:gap-16";const titleSize=device==="mobile"?"text-3xl":device?"text-4xl":"text-3xl sm:text-4xl";return <section className={`w-full bg-secondary/30 ${padding}`} style={{...themeTokenStyle(tokens),...projectTokenStyle(tokens)}}><div className={`mx-auto grid max-w-6xl ${layout}`}><header><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-primary"><InlineEditableText node={node} propKey="eyebrow" value={eyebrow} fallback="Pertanyaan yang sering muncul" /></p><h2 className={`mt-3 font-[family-name:var(--font-heading)] font-extrabold leading-tight tracking-[-0.045em] text-foreground ${titleSize}`}><InlineEditableText node={node} propKey="title" value={title} fallback="Semua yang perlu Anda tahu sebelum mulai." multiline /></h2><p className="mt-4 text-sm leading-6 text-muted-foreground"><InlineEditableText node={node} propKey="description" value={description} fallback="Jika jawabannya belum ada di sini, Anda selalu bisa menghubungi kami untuk berdiskusi." multiline /></p></header><div className="divide-y divide-border rounded-[var(--radius)] border border-border bg-card px-5">{items(node).map((item,index)=><details key={item.id} className="group py-1" open={index===0}><summary className="flex min-h-15 cursor-pointer list-none items-center justify-between gap-4 py-4 text-left text-sm font-bold text-foreground [&::-webkit-details-marker]:hidden"><span><InlineEditableText node={node} propKey="items" value={item.question} onCommit={(next)=>setValue(index,"question",next)} /></span><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-secondary text-primary transition-transform duration-200 group-open:rotate-180"><ChevronDown size={16} aria-hidden="true"/></span></summary><p className="max-w-xl pb-5 text-sm leading-6 text-muted-foreground"><InlineEditableText node={node} propKey="items" value={item.answer} onCommit={(next)=>setValue(index,"answer",next)} multiline /></p></details>)}</div></div></section>;}
