import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString } from "@/lib/registry/shared";
import { listValue, nodeList, uniqueId } from "../_shared/content";

type Status = "success" | "pending" | "warning";
type Activity = { id: string; initials: string; title: string; description: string; time: string; status: Status };
const FALLBACK: Activity[] = [
  { id: "nadia", initials: "NA", title: "Nadia mengundang anggota baru", description: "Tim desain sekarang memiliki akses ke workspace utama.", time: "Baru saja", status: "success" },
  { id: "rangga", initials: "RP", title: "Laporan penjualan siap ditinjau", description: "Ringkasan periode Juli sudah diperbarui dengan data terbaru.", time: "12 menit lalu", status: "pending" },
  { id: "dika", initials: "DK", title: "Ada pembayaran yang perlu dicek", description: "Satu transaksi menunggu konfirmasi dari tim keuangan.", time: "1 jam lalu", status: "warning" },
  { id: "salsa", initials: "SM", title: "Salsa menyelesaikan catatan proyek", description: "Semua perubahan pada brief kampanye sudah tersimpan.", time: "Kemarin", status: "success" },
];
function safeStatus(value: string): Status { return value === "pending" || value === "warning" ? value : "success"; }
function itemSource(node: Node) { return node.props.items === undefined ? "itemsJson" : "items"; }
function activities(node: Node): Activity[] { const entries = nodeList(node, itemSource(node)).map((item, index) => { const title = listValue(item, "title"); if (!title) return null; return { id: uniqueId("activity", index, title), initials: listValue(item, "initials", title.slice(0, 2).toUpperCase()).slice(0, 3), title, description: listValue(item, "description"), time: listValue(item, "time", "Baru saja"), status: safeStatus(listValue(item, "status", "success")) }; }).filter((item): item is Activity => item !== null); return entries.length ? entries : FALLBACK; }
function copy(node: Node, key: string, fallback: string) { return propString(node, key).trim() || fallback; }
const STATUS = { success: { label: "Selesai", mark: "✓" }, pending: { label: "Menunggu", mark: "◷" }, warning: { label: "Perlu cek", mark: "!" } };

export function dashboardActivityListExport(node: Node): ExportResult {
  const title = copy(node, "title", "Aktivitas terbaru"); const description = copy(node, "description", "Pembaruan yang perlu diketahui tim hari ini.");
  const entries = activities(node).map((item) => { const status = STATUS[item.status]; return `<article class="bi-activity-item"><span class="bi-activity-avatar">${escapeHtml(item.initials)}</span><div class="bi-activity-copy"><div><h4>${escapeHtml(item.title)}</h4><time>${escapeHtml(item.time)}</time></div>${item.description ? `<p>${escapeHtml(item.description)}</p>` : ""}<span class="bi-activity-status bi-activity-status--${item.status}"><b aria-hidden="true">${status.mark}</b>${status.label}</span></div></article>`; }).join("\n");
  return { html: `<article class="bi-activity-list"><header><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(description)}</p></div><button type="button" aria-label="Pilihan aktivitas">•••</button></header><div class="bi-activity-entries">${entries}</div></article>`, css: `.bi-activity-list{width:100%;min-width:0;overflow:hidden;border:1px solid var(--bi-border);border-radius:calc(var(--bi-radius) * 1.05);background:var(--bi-card);color:var(--bi-fg);box-shadow:0 1px 2px color-mix(in srgb,var(--bi-fg) 5%,transparent);font-family:var(--bi-font-body)}.bi-activity-list>header{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem;padding:1rem 1.25rem;border-bottom:1px solid var(--bi-border)}.bi-activity-list h3{margin:0;font:800 1rem/1.25 var(--bi-font-heading);letter-spacing:-.025em}.bi-activity-list header p{margin:.25rem 0 0;color:var(--bi-muted-fg);font-size:.75rem}.bi-activity-list header button{display:grid;width:2rem;height:2rem;flex:none;place-items:center;border:0;border-radius:calc(var(--bi-radius) * .65);background:transparent;color:var(--bi-muted-fg);cursor:pointer}.bi-activity-list header button:hover{background:var(--bi-muted);color:var(--bi-fg)}.bi-activity-entries{display:grid}.bi-activity-item{display:flex;min-width:0;gap:.75rem;padding:.875rem 1.25rem;border-top:1px solid var(--bi-border);transition:background .15s ease}.bi-activity-item:first-child{border-top:0}.bi-activity-item:hover{background:color-mix(in srgb,var(--bi-muted) 45%,transparent)}.bi-activity-avatar{display:grid;width:2.25rem;height:2.25rem;flex:none;place-items:center;border-radius:50%;background:color-mix(in srgb,var(--bi-primary) 10%,transparent);color:var(--bi-primary);font-size:.65rem;font-weight:850}.bi-activity-copy{min-width:0;flex:1}.bi-activity-copy>div{display:flex;min-width:0;align-items:center;justify-content:space-between;gap:.75rem}.bi-activity-copy h4{min-width:0;overflow:hidden;margin:0;font-size:.85rem;font-weight:750;text-overflow:ellipsis;white-space:nowrap}.bi-activity-copy time{flex:none;color:var(--bi-muted-fg);font-size:.625rem;font-weight:600}.bi-activity-copy>p{margin:.25rem 0 0;color:var(--bi-muted-fg);font-size:.75rem;line-height:1.55}.bi-activity-status{display:inline-flex;align-items:center;gap:.25rem;margin-top:.45rem;padding:.2rem .45rem;border-radius:999px;font-size:.6rem;font-weight:800}.bi-activity-status--success{background:color-mix(in srgb,#10b981 12%,transparent);color:#047857}.bi-activity-status--pending{background:color-mix(in srgb,#0ea5e9 12%,transparent);color:#0369a1}.bi-activity-status--warning{background:color-mix(in srgb,#f59e0b 14%,transparent);color:#b45309}@media(max-width:560px){.bi-activity-list>header,.bi-activity-item{padding-inline:1rem}}` };
}
