import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString } from "@/lib/registry/shared";
import { arrayNavigationLinks, navInstanceId } from "../_shared/navigation";

export function dropdownMenuExport(node: Node): ExportResult {
  const buttonText = propString(node, "buttonText").trim() || "Lihat pilihan";
  const align = propString(node, "align") === "right" ? "right" : "left";
  const instance = navInstanceId(node, "dropdown"); const listId = `${instance}-list`;
  const items = arrayNavigationLinks(node, "items", [
    { id: "layanan", label: "Layanan kami", url: "#layanan" }, { id: "karya", label: "Karya terbaru", url: "#karya" }, { id: "tentang", label: "Tentang studio", url: "#tentang" },
  ]).map((item, index) => `<a href="${escapeHtml(item.url)}"><span>${escapeHtml(item.label)}</span>${index === 0 ? '<b aria-hidden="true">✓</b>' : '<i aria-hidden="true"></i>'}</a>`).join("");
  return { html: `<div class="bi-dropdown bi-dropdown--${align}" data-bi-dropdown="${instance}" data-open="false"><button type="button" data-bi-dropdown-toggle aria-expanded="false" aria-controls="${listId}">${escapeHtml(buttonText)} <span aria-hidden="true">⌄</span></button><div class="bi-dropdown-list" id="${listId}">${items}</div></div>`, css: `.bi-dropdown{position:relative;z-index:12;display:inline-flex;max-width:100%;padding:1rem;color:var(--bi-fg);font-family:var(--bi-font-body)}.bi-dropdown>button{display:inline-flex;align-items:center;gap:.45rem;padding:.7rem 1rem;border:1px solid var(--bi-border);border-radius:999px;background:var(--bi-card);box-shadow:0 1px 2px rgba(0,0,0,.04);color:var(--bi-fg);font:800 .86rem/1 var(--bi-font-body);cursor:pointer;transition:transform .2s ease,box-shadow .2s ease}.bi-dropdown>button:hover{transform:translateY(-2px);box-shadow:var(--bi-shadow)}.bi-dropdown>button span{transition:transform .2s ease}.bi-dropdown[data-open="true"]>button span{transform:rotate(180deg)}.bi-dropdown-list{position:absolute;top:calc(100% - .1rem);display:grid;min-width:14rem;padding:.35rem;border:1px solid var(--bi-border);border-radius:var(--bi-radius);background:var(--bi-card);box-shadow:var(--bi-shadow);opacity:0;pointer-events:none;transform:translateY(-.3rem);transition:opacity .18s ease,transform .18s ease}.bi-dropdown--left .bi-dropdown-list{left:1rem}.bi-dropdown--right .bi-dropdown-list{right:1rem}.bi-dropdown[data-open="true"] .bi-dropdown-list{opacity:1;pointer-events:auto;transform:translateY(0)}.bi-dropdown-list a{display:flex;align-items:center;justify-content:space-between;gap:.75rem;padding:.7rem .75rem;border-radius:calc(var(--bi-radius) * .7);color:var(--bi-fg);font-size:.87rem;font-weight:650;text-decoration:none;transition:background .18s ease}.bi-dropdown-list a:hover{background:var(--bi-muted)}.bi-dropdown-list b{color:var(--bi-primary)}.bi-dropdown-list i{width:.38rem;height:.38rem;border-radius:50%;background:var(--bi-border);transition:background .18s ease}.bi-dropdown-list a:hover i{background:var(--bi-primary)}`, js: `document.querySelectorAll('[data-bi-dropdown="${instance}"]').forEach(function(root){var toggle=root.querySelector('[data-bi-dropdown-toggle]');function close(){root.dataset.open='false';toggle.setAttribute('aria-expanded','false');}toggle.addEventListener('click',function(event){event.stopPropagation();var open=root.dataset.open==='true';root.dataset.open=String(!open);toggle.setAttribute('aria-expanded',String(!open));});document.addEventListener('click',function(event){if(!root.contains(event.target))close();});document.addEventListener('keydown',function(event){if(event.key==='Escape')close();});root.querySelectorAll('.bi-dropdown-list a').forEach(function(link){link.addEventListener('click',close);});});` };
}
