import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString } from "@/lib/registry/shared";
import { listValue, nodeList, uniqueId } from "../_shared/content";
interface Stat { id:string; value:string; suffix:string; label:string; }
const FALLBACK: Stat[] = [{id:"projects",value:"74",suffix:"+",label:"proyek diluncurkan"},{id:"years",value:"8",suffix:" tahun",label:"menemani bisnis tumbuh"},{id:"return",value:"96",suffix:"%",label:"klien kembali bekerja sama"},{id:"cities",value:"12",suffix:" kota",label:"kolaborasi lintas Indonesia"}];
function stats(node:Node):Stat[] { const list=nodeList(node,"stats").map((item,index)=>{const value=listValue(item,"value");if(!value)return null;return{id:uniqueId("stat",index,listValue(item,"label",value)),value,suffix:listValue(item,"suffix"),label:listValue(item,"label")};}).filter((item):item is Stat=>item!==null);return list.length?list:FALLBACK; }
function background(node:Node){const value=propString(node,"sectionBg");return value==="default"||value==="muted"||value==="foreground"||value==="primary"?value:"primary";}
export function statsBannerExport(node:Node):ExportResult { const eyebrow=propString(node,"eyebrow").trim()||"Dibangun bersama mitra kami";const title=propString(node,"title").trim()||"Bukti kerja yang bisa dilihat, bukan sekadar janji.";const bg=background(node);const items=stats(node).map((item)=>`<div class="bi-stat"><strong>${escapeHtml(item.value)}<small>${escapeHtml(item.suffix)}</small></strong><p>${escapeHtml(item.label)}</p></div>`).join("");return{html:`<section class="bi-stats is-${bg}"><div class="bi-container"><header><p>${escapeHtml(eyebrow)}</p><h2 class="bi-title">${escapeHtml(title)}</h2></header><div class="bi-stats-grid">${items}</div></div></section>`,css:`.bi-stats { padding-block:clamp(3.5rem,8vw,6.5rem); color:var(--bi-fg); background:var(--bi-primary); }.bi-stats.is-default{background:var(--bi-bg)}.bi-stats.is-muted{background:var(--bi-secondary)}.bi-stats.is-foreground{background:var(--bi-fg);color:var(--bi-bg)}.bi-stats.is-primary{color:var(--bi-primary-fg)}.bi-stats header{max-width:34rem}.bi-stats header>p{margin:0;color:currentColor;font-size:.68rem;font-weight:800;letter-spacing:.14em;opacity:.72;text-transform:uppercase}.bi-stats h2{margin:.75rem 0 0;color:currentColor}.bi-stats-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));overflow:hidden;margin-top:2.5rem;border:1px solid color-mix(in srgb,currentColor 20%,transparent);border-radius:var(--bi-radius)}.bi-stat{min-width:0;padding:1.25rem;border-left:1px solid color-mix(in srgb,currentColor 20%,transparent)}.bi-stat:first-child{border-left:0}.bi-stat strong{font:800 clamp(1.8rem,3vw,2.6rem)/1 var(--bi-font-heading);letter-spacing:-.06em}.bi-stat small{margin-left:.12rem;font:700 .9rem/1 var(--bi-font-body);letter-spacing:normal}.bi-stat p{margin:.65rem 0 0;font-size:.78rem;line-height:1.5;opacity:.72}@media(max-width:760px){.bi-stats-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.bi-stat:nth-child(odd){border-left:0}.bi-stat:nth-child(n+3){border-top:1px solid color-mix(in srgb,currentColor 20%,transparent)}}`}; }
