import type { RawTemplateNode } from "@/templates";

/** Agensi kreatif digital — terinspirasi dari template "bino". */
export function createAgensiKreatifNodes(): RawTemplateNode[] {
  return [
    {
      id: "bino-nav",
      componentType: "navbar-minimal",
      name: "Navigasi Bino",
      props: {
        logoText: "bino",
        link1Text: "Layanan",
        link1Url: "#layanan",
        link2Text: "Karya",
        link2Url: "#karya",
        link3Text: "Cerita klien",
        link3Url: "#cerita",
        ctaText: "Mulai proyek",
        ctaUrl: "#mulai",
      },
      styles: { padding: "none" },
    },
    {
      id: "bino-hero",
      componentType: "hero-split",
      name: "Hero Bino",
      props: {
        badgeText: "Agensi kreatif untuk brand yang ingin dikenal",
        title: "Kami membuat brand yang sulit dilupakan.",
        description:
          "Bino membantu startup dan perusahaan menengah membangun identitas, website, dan kampanye yang menyatu — dari strategi hingga desain akhir.",
        primaryCtaText: "Konsultasi gratis",
        primaryCtaUrl: "#mulai",
        secondaryCtaText: "Lihat karya",
        secondaryCtaUrl: "#karya",
        imageUrl:
          "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Tim kreatif sedang brainstorming di depan papan sticky notes",
        supportingText: "Sudah dipercaya 60+ brand sejak 2019.",
        imageBadgeText: "EST. 2019",
        imageNoteLabel: "Studio kami",
        imageNoteText: "Strategi, desain, dan pengembangan dalam satu atap.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "bino-klien",
      componentType: "logo-clients",
      name: "Klien yang Percaya",
      props: {
        eyebrow: "Dipercaya brand yang sedang bertumbuh",
        logosJson: [
          { name: "Aruna", url: "#" },
          { name: "Kopi Nusantara", url: "#" },
          { name: "Pesona Tour", url: "#" },
          { name: "Sekawan", url: "#" },
          { name: "Lantai Studio", url: "#" },
          { name: "Matahari Farma", url: "#" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "bino-layanan",
      componentType: "grid-container",
      name: "Layanan Bino",
      props: { columns: "3", gap: "md" },
      styles: { padding: "xl" },
      children: [
        {
          id: "bino-layanan-1",
          componentType: "card-feature",
          name: "Layanan Identitas",
          props: {
            icon: "sparkles",
            eyebrow: "01 · Identitas",
            title: "Brand yang punya kepribadian.",
            description: "Riset, strategi merek, sistem visual, dan panduan penggunaan yang siap dipakai tim Anda.",
            linkText: "Lihat pendekatan",
            linkUrl: "#karya",
          },
        },
        {
          id: "bino-layanan-2",
          componentType: "card-feature",
          name: "Layanan Website",
          props: {
            icon: "layers",
            eyebrow: "02 · Digital",
            title: "Website yang menjual, bukan sekadar pajangan.",
            description: "Desain antarmuka, pengembangan, dan optimasi konversi dengan standar aksesibilitas yang baik.",
            linkText: "Lihat kasus studi",
            linkUrl: "#karya",
          },
        },
        {
          id: "bino-layanan-3",
          componentType: "card-feature",
          name: "Layanan Kampanye",
          props: {
            icon: "megaphone",
            eyebrow: "03 · Kampanye",
            title: "Kampanye yang punya arah dan cerita.",
            description: "Perencanaan konten, produksi visual, dan distribusi di kanal yang paling relevan untuk audiens Anda.",
            linkText: "Lihat hasil",
            linkUrl: "#cerita",
          },
        },
      ],
    },
    {
      id: "bino-karya",
      componentType: "gallery-grid",
      name: "Karya Pilihan",
      props: {
        sectionId: "karya",
        eyebrow: "Karya pilihan",
        title: "Pekerjaan yang membuat kami bangga.",
        description: "Sebagian dari proyek identitas dan digital yang selesai dalam dua tahun terakhir.",
        columns: "3",
        images: [
          {
            url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=85",
            title: "Rebrand Kopi Nusantara",
            caption: "Identitas & kemasan · 2025",
            alt: "Kemasan kopi dengan desain modern",
          },
          {
            url: "https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=85",
            title: "Website Pesona Tour",
            caption: "Desain & pengembangan · 2025",
            alt: "Tampilan website agen perjalanan",
          },
          {
            url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=1200&q=85",
            title: "Kampanye Sekawan",
            caption: "Kampanye peluncuran · 2024",
            alt: "Poster kampanye dengan warna berani",
          },
          {
            url: "https://images.unsplash.com/photo-1634942537034-2531766767d1?auto=format&fit=crop&w=1200&q=85",
            title: "Identitas Lantai Studio",
            caption: "Sistem visual · 2024",
            alt: "Kartu nama dan materi identitas studio",
          },
          {
            url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=85",
            title: "Aplikasi Aruna",
            caption: "Desain produk · 2024",
            alt: "Antarmuka aplikasi di layar ponsel",
          },
          {
            url: "https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&w=1200&q=85",
            title: "Website Matahari Farma",
            caption: "Desain & pengembangan · 2023",
            alt: "Tampilan website perusahaan farmasi",
          },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "bino-cerita",
      componentType: "testimonial-grid",
      name: "Cerita Klien",
      props: {
        sectionId: "cerita",
        eyebrow: "Cerita klien",
        title: "Yang mereka katakan setelah bekerja sama.",
        description: "Kutipan dari klien yang sudah menuntaskan proyek bersama Bino.",
        columns: "3",
        items: [
          {
            quote: "Dalam enam bulan, brand awareness kami naik 38% dan traffic website bertambah dua kali lipat. Prosesnya sangat terarah.",
            name: "Andi Prasetyo",
            role: "Founder, Kopi Nusantara",
            initials: "AP",
          },
          {
            quote: "Bino bukan sekadar vendor desain. Mereka menantang keputusan kami dengan data, dan hasilnya terasa di penjualan.",
            name: "Ratna Kusuma",
            role: "CMO, Pesona Tour",
            initials: "RK",
          },
          {
            quote: "Pekerjaan selesai sesuai jadwal, komunikasi rapi, dan timnya benar-benar memahami produk kami.",
            name: "Dimas Saputra",
            role: "CEO, Sekawan",
            initials: "DS",
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "bino-newsletter",
      componentType: "form-newsletter",
      name: "Berlangganan Bino",
      props: {
        eyebrow: "Tetap terhubung",
        heading: "Satu email sebulan tentang strategi brand.",
        description: "Rangkuman kasus, riset, dan panduan praktis yang bisa langsung dipakai tim Anda. Tanpa spam.",
        placeholder: "nama@perusahaan.com",
        buttonText: "Berlangganan",
        note: "Bisa berhenti kapan saja. 4.200 pembaca aktif.",
        successText: "Terima kasih sudah berlangganan. Email pertama menyusul bulan depan.",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "bino-cta",
      componentType: "cta-basic",
      name: "Ajakan Mulai Proyek",
      props: {
        title: "Punya proyek yang ingin didiskusikan?",
        description: "Konsultasi pertama gratis dan tanpa komitmen. Kami balas maksimal satu hari kerja.",
        buttonText: "Mulai percakapan",
        buttonUrl: "#mulai",
        secondaryText: "Lihat karya",
        secondaryUrl: "#karya",
      },
      styles: { padding: "xl" },
    },
    {
      id: "bino-footer",
      componentType: "footer-basic",
      name: "Footer Bino",
      props: {
        brandName: "bino",
        tagline: "Agensi kreatif digital. Jl. Senopati No. 12, Jakarta Selatan. Email halo@bino.id.",
        link1Text: "Layanan",
        link1Url: "#layanan",
        link2Text: "Karya",
        link2Url: "#karya",
        link3Text: "halo@bino.id",
        link3Url: "mailto:halo@bino.id",
        copyrightText: "© 2026 Bino Creative Agency.",
      },
      styles: { padding: "none" },
    },
    {
      id: "bino-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}