import type { RawTemplateNode } from "@/templates";

/** Trust-building company profile with information architecture ready for a real business. */
export function createCompanyLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "company-nav",
      componentType: "navbar-centered",
      name: "Navigasi Karya Utama",
      props: {
        logoText: "KARYA UTAMA",
        link1Text: "Beranda",
        link1Url: "#",
        link2Text: "Layanan",
        link2Url: "#layanan",
        link3Text: "Tim",
        link3Url: "#tim",
        link4Text: "Cerita",
        link4Url: "#cerita",
        ctaText: "Konsultasi",
        ctaUrl: "#kontak",
      },
      styles: { padding: "none" },
    },
    {
      id: "company-hero",
      componentType: "hero-centered",
      name: "Hero Karya Utama",
      props: {
        badgeText: "Strategi, identitas, dan digital experience",
        title: "Membantu bisnis tumbuh dengan arah yang mudah dipahami.",
        description:
          "Kami adalah partner untuk bisnis yang ingin menyatukan strategi, identitas, dan website menjadi pengalaman yang terasa jelas bagi pelanggan.",
        primaryCtaText: "Jadwalkan konsultasi",
        primaryCtaUrl: "#kontak",
        secondaryCtaText: "Lihat layanan",
        secondaryCtaUrl: "#layanan",
        imageUrl:
          "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Tim perusahaan berdiskusi dan bekerja bersama di ruang modern",
        supportingText: "Berangkat dari konteks bisnis Anda, lalu tumbuh menjadi sistem yang bisa dipakai tim.",
        imageBadgeText: "SINCE 2014",
      },
      styles: { padding: "xl" },
    },
    {
      id: "company-stats",
      componentType: "stats-banner",
      name: "Pencapaian Karya Utama",
      props: {
        eyebrow: "Tumbuh bersama klien",
        title: "Pekerjaan yang baik selalu meninggalkan cara kerja yang lebih baik.",
        sectionBg: "foreground",
        stats: [
          { value: "128", suffix: "+", label: "proyek bisnis diluncurkan" },
          { value: "41", suffix: " industri", label: "dipahami lebih dalam" },
          { value: "89", suffix: "%", label: "klien datang lewat rekomendasi" },
          { value: "12", suffix: " tahun", label: "menjaga kualitas proses" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "company-services",
      componentType: "grid-container",
      name: "Layanan Karya Utama",
      props: { columns: "3", gap: "md" },
      styles: { padding: "xl", background: "muted" },
      children: [
        {
          id: "company-service-1",
          componentType: "card-feature",
          name: "Strategi Bisnis",
          props: {
            icon: "chart",
            eyebrow: "01 / Strategi",
            title: "Menentukan arah sebelum memperbesar suara.",
            description: "Memetakan apa yang penting bagi bisnis, pelanggan, dan keputusan yang akan diambil berikutnya.",
            linkText: "Pelajari strategi",
            linkUrl: "#kontak",
          },
        },
        {
          id: "company-service-2",
          componentType: "card-feature",
          name: "Identitas Brand",
          props: {
            icon: "layers",
            eyebrow: "02 / Identitas",
            title: "Membuat sistem yang konsisten namun tetap hidup.",
            description: "Nama, pesan, dan bahasa visual yang bisa dipakai percaya diri oleh seluruh tim Anda.",
            linkText: "Pelajari identitas",
            linkUrl: "#kontak",
          },
        },
        {
          id: "company-service-3",
          componentType: "card-feature",
          name: "Pengalaman Digital",
          props: {
            icon: "globe",
            eyebrow: "03 / Digital",
            title: "Menjadikan website tempat pelanggan memahami Anda.",
            description: "Arsitektur konten dan antarmuka responsif yang mengarahkan orang menuju keputusan yang tepat.",
            linkText: "Pelajari digital",
            linkUrl: "#kontak",
          },
        },
      ],
    },
    {
      id: "company-team",
      componentType: "team-grid",
      name: "Tim Karya Utama",
      props: {
        eyebrow: "Orang di balik pekerjaan",
        title: "Tim lintas disiplin yang tetap senang duduk satu meja.",
        description: "Strategi tidak berdiri sendiri dari desain, dan desain tidak berjalan jauh tanpa memahami bisnisnya.",
        columns: "4",
        members: [
          { name: "Dije Pramana", role: "Managing Director", initials: "DP", imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Ignas Wirawan", role: "Strategy Director", initials: "IW", imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Alya Pradipta", role: "Design Lead", initials: "AP", imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Raka Syahputra", role: "Digital Lead", initials: "RS", imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "company-testimonials",
      componentType: "testimonial-grid",
      name: "Testimoni Klien",
      props: {
        eyebrow: "Kerja bersama yang terasa",
        title: "Kami ingin setiap keputusan memudahkan pekerjaan klien setelah proyek selesai.",
        description: "Bukan sekadar menghadirkan sesuatu yang baru, tetapi meninggalkan sistem yang dapat dijalankan tim sendiri.",
        columns: "3",
        items: [
          { quote: "Mereka tidak hanya mendesain ulang tampilan. Tim kami akhirnya memiliki bahasa yang sama saat berbicara kepada pelanggan.", name: "Risa Kurnia", role: "Chief Marketing Officer, Tumbuh", initials: "RK" },
          { quote: "Cara mereka menggali konteks membuat kami melihat bisnis sendiri dengan lebih jernih. Keputusannya jadi jauh lebih cepat.", name: "Andra Halim", role: "Director, Rimba", initials: "AH" },
          { quote: "Dari strategi sampai website, semuanya terasa tersambung. Tidak ada bagian yang dibuat sekadar untuk terlihat bagus.", name: "Maya Sari", role: "Founder, Sela Living", initials: "MS" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "company-cta",
      componentType: "cta-basic",
      name: "Ajakan Konsultasi Karya Utama",
      props: {
        title: "Mari lihat apakah kita bisa membuat langkah berikutnya terasa lebih jelas.",
        description: "Satu sesi perkenalan cukup untuk membahas konteks, kebutuhan, dan kemungkinan arah kerja sama.",
        buttonText: "Mulai konsultasi",
        buttonUrl: "mailto:halo@karyautama.id",
        secondaryText: "Lihat layanan",
        secondaryUrl: "#layanan",
      },
      styles: { padding: "xl" },
    },
    {
      id: "company-footer",
      componentType: "footer-basic",
      name: "Footer Karya Utama",
      props: {
        brandName: "KARYA UTAMA",
        tagline: "Partner strategi, identitas, dan pengalaman digital untuk bisnis yang ingin bergerak dengan lebih terarah.",
        link1Text: "Layanan",
        link1Url: "#layanan",
        link2Text: "Tim",
        link2Url: "#tim",
        link3Text: "halo@karyautama.id",
        link3Url: "mailto:halo@karyautama.id",
        copyrightText: "© 2026 Karya Utama. Semua hak dilindungi.",
      },
      styles: { padding: "none" },
    },
  ];
}
