import type { RawTemplateNode } from "@/templates";

/** Konferensi produk dengan tiket, pembicara, dokumentasi, dan FAQ peserta. */
export function createEventLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "event-nav",
      componentType: "navbar-glass",
      name: "Navigasi Ngobrolin Produk",
      props: {
        logoText: "NGOPROLIN PRODUK",
        link1Text: "Rundown",
        link1Url: "#rundown",
        link2Text: "Pembicara",
        link2Url: "#pembicara",
        link3Text: "Tiket",
        link3Url: "#tiket",
        ctaText: "Daftar sekarang",
        ctaUrl: "#daftar",
      },
      styles: { padding: "none" },
    },
    {
      id: "event-hero",
      componentType: "hero-bg-image",
      name: "Hero Ngobrolin Produk 2026",
      props: {
        badgeText: "10–12 Oktober 2026 · Jakarta",
        title: "Tiga hari untuk bertukar praktik nyata dari tim produk.",
        description:
          "Ngobrolin Produk 2026 menghadirkan 30 pembicara dari studio dan perusahaan teknologi di Indonesia. Sesi utama, workshop kecil, dan pameran komunitas di Balai Kartini, Jakarta.",
        primaryCtaText: "Daftar sekarang",
        primaryCtaUrl: "#daftar",
        secondaryCtaText: "Lihat rundown",
        secondaryCtaUrl: "#rundown",
        imageUrl:
          "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Penonton memenuhi aula konferensi dengan layar besar",
        supportingText: "1.200 peserta · 30 pembicara · 3 hari",
        imageBadgeText: "JAKARTA · 2026",
      },
      styles: { padding: "xl" },
    },
    {
      id: "event-cara",
      componentType: "process-steps",
      name: "Cara Ikut Ngobrolin Produk",
      props: {
        eyebrow: "Cara ikut",
        heading: "Daftar dalam tiga langkah.",
        stepsJson: JSON.stringify([
          {
            id: "e1",
            title: "Daftar & pilih tiket",
            description: "Pilih jenis tiket lalu isi data peserta lewat form pendaftaran di halaman ini.",
          },
          {
            id: "e2",
            title: "Terima e-tiket",
            description: "E-tiket masuk dan rundown dikirim ke email maksimal tiga hari sebelum acara dimulai.",
          },
          {
            id: "e3",
            title: "Hadir & scan",
            description: "Tunjukkan e-tiket di pintu masuk Balai Kartini. Cetak atau cukup dari ponsel.",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "event-tiket",
      componentType: "pricing-table",
      name: "Tiket Ngobrolin Produk",
      props: {
        eyebrow: "Tiket",
        title: "Tiga pilihan tiket untuk tiga cara mengikuti acara.",
        description: "Semua tiket mencakup akses sesi utama selama tiga hari. Kuota Early Bird terbatas 200 tiket pertama.",
        plans: [
          {
            name: "Early Bird",
            price: "Rp 350.000",
            period: "/tiket",
            description: "Harga awal untuk 200 tiket pertama.",
            features: ["Akses 3 hari sesi utama", "Coffee break", "E-sertifikat peserta"],
            buttonText: "Pilih Early Bird",
            buttonUrl: "#daftar",
            highlighted: false,
          },
          {
            name: "Reguler",
            price: "Rp 450.000",
            period: "/tiket",
            description: "Harga normal yang berlaku mulai 1 Juli 2026.",
            features: ["Akses 3 hari sesi utama", "Coffee break", "E-sertifikat peserta", "Kaos acara"],
            buttonText: "Pilih Reguler",
            buttonUrl: "#daftar",
            highlighted: true,
          },
          {
            name: "VIP",
            price: "Rp 750.000",
            period: "/tiket",
            description: "Kursi zona depan dan makan siang setiap hari.",
            features: ["Semua akses Reguler", "Kursi zona depan", "Makan siang 3 hari", "Networking dinner"],
            buttonText: "Pilih VIP",
            buttonUrl: "#daftar",
            highlighted: false,
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "event-pembicara",
      componentType: "team-grid",
      name: "Pembicara Ngobrolin Produk",
      props: {
        eyebrow: "Pembicara",
        title: "Orang yang membawa kerja nyata, bukan sekadar judul.",
        description: "Empat dari tiga puluh pembicara yang akan berbagi studi kasus di sesi utama hari pertama.",
        columns: "4",
        members: [
          { name: "Andi Prasetyo", role: "Product Lead, Loket.id", initials: "AP", imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Rani Kusuma", role: "Design Director, Kiosk Studio", initials: "RK", imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Dimas Arya", role: "Engineering Manager, Bank Sahabat", initials: "DA", imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
          { name: "Maya Lestari", role: "UX Researcher, Rumah Produk", initials: "ML", imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80", socialUrl: "#" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "event-galeri",
      componentType: "gallery-grid",
      name: "Dokumentasi Acara",
      props: {
        eyebrow: "Dokumentasi",
        title: "Potongan suasana dari acara tahun lalu di Semarang.",
        description: "Foto diambil oleh fotografer peserta komunitas tanpa panggung yang berlebihan.",
        columns: "3",
        images: [
          { url: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1000&q=85", alt: "Pembicara di atas panggung dengan layar presentasi", title: "Sesi pembuka", caption: "Main stage" },
          { url: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=85", alt: "Peserta berdiskusi di meja bundar", title: "Diskusi kelompok", caption: "Workshop" },
          { url: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1000&q=85", alt: "Salah satu peserta sedang presentasi", title: "Sesi praktik", caption: "Workshop" },
          { url: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1000&q=85", alt: "Kelompok peserta saling bertukar kartu nama", title: "Istirahat makan", caption: "Networking" },
          { url: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1000&q=85", alt: "Banyak peserta duduk di aula konferensi", title: "Sesi siang", caption: "Main stage" },
          { url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1000&q=85", alt: "Aula penuh dengan peserta konferensi", title: "Hari kedua", caption: "Main stage" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "event-testimoni",
      componentType: "testimonial-grid",
      name: "Testimoni Peserta",
      props: {
        eyebrow: "Kata peserta",
        title: "Mereka yang duduk di kursi yang sama dengan Anda.",
        description: "Kutipan dari peserta acara tahun sebelumnya yang kami minta izin untuk ditampilkan.",
        columns: "3",
        items: [
          { quote: "Tahun lalu saya datang sendiri, pulangnya mendapat 12 kenalan kerja baru.", name: "Fajar Nugroho", role: "UI Designer, Jakarta", initials: "FN" },
          { quote: "Sesi workshop-nya praktis—langsung bisa dipakai Senin pagi di kantor.", name: "Intan Permata", role: "Product Manager, Bandung", initials: "IP" },
          { quote: "Salah satu acara produk yang jadwalnya selalu on time sampai sesi terakhir.", name: "Yoga Saputra", role: "Founder, Studio Tiga", initials: "YS" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "event-faq",
      componentType: "faq-accordion",
      name: "FAQ Ngobrolin Produk",
      props: {
        eyebrow: "Pertanyaan umum",
        title: "Tiket, refund, dan lokasi—dijawab ringkas.",
        description: "Pertanyaan lain bisa dikirim ke panitia lewat email atau WhatsApp resmi.",
        items: [
          { question: "Apakah tiket bisa refund?", answer: "Pengembalian dana penuh tersedia hingga 30 September 2026. Setelah tanggal itu, tiket bisa dialihkan ke nama lain tanpa biaya." },
          { question: "Di mana lokasi acara?", answer: "Balai Kartini, Jl. Gatot Subroto No. 37, Jakarta Selatan. Parkir tersedia dan berjarak 5 menit jalan kaki dari halte TransJakarta Gatot Subroto." },
          { question: "Apakah tiket dijual di hari-H?", answer: "Tergantung kuota. Kami sarankan membeli lebih awal—tahun lalu tiket Early Bird habis dalam dua minggu." },
          { question: "Apakah acara bisa diikuti tanpa tiket?", answer: "Tidak. Semua sesi dan pameran komunitas hanya bisa diakses dengan tiket yang sudah dibeli." },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "event-cta",
      componentType: "cta-basic",
      name: "Ajakan Daftar Ngobrolin Produk",
      props: {
        title: "Kursi terbatas untuk 1.200 peserta.",
        description: "Satu tiket sudah termasuk tiga hari sesi utama, coffee break, dan e-sertifikat. Daftar sebelum 30 Juni untuk harga Early Bird.",
        buttonText: "Daftar sekarang",
        buttonUrl: "#daftar",
        secondaryText: "Lihat rundown",
        secondaryUrl: "#rundown",
      },
      styles: { padding: "xl" },
    },
    {
      id: "event-footer",
      componentType: "footer-basic",
      name: "Footer Ngobrolin Produk",
      props: {
        brandName: "NGOPROLIN PRODUK",
        tagline: "Konferensi tahunan untuk tim produk Indonesia, 10–12 Oktober 2026 di Balai Kartini, Jakarta.",
        link1Text: "Tiket",
        link1Url: "#tiket",
        link2Text: "Pembicara",
        link2Url: "#pembicara",
        link3Text: "halo@ngobrolinproduk.id",
        link3Url: "mailto:halo@ngobrolinproduk.id",
        copyrightText: "© 2026 Ngobrolin Produk. Diselenggarakan oleh Komunitas Produk Jakarta.",
      },
      styles: { padding: "none" },
    },
  ];
}
