import type { RawTemplateNode } from "@/templates";

/** Retail landing that treats desktop and mobile as distinct editorial compositions. */
export function createFashionLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "fashion-nav",
      componentType: "navbar-split",
      name: "Navigasi Luma Objects",
      props: {
        logoText: "LUMA OBJECTS",
        link1Text: "Koleksi",
        link1Url: "#koleksi",
        link2Text: "Cerita",
        link2Url: "#cerita",
        link3Text: "Kunjungi",
        link3Url: "#kontak",
        ctaText: "Lihat koleksi",
        ctaUrl: "#koleksi",
      },
      styles: { padding: "none" },
    },
    {
      id: "fashion-hero",
      componentType: "hero-bg-image",
      name: "Hero Luma Objects",
      props: {
        badgeText: "Autumn / Winter 2026",
        title: "Benda untuk ruang yang dipakai, bukan hanya dipandangi.",
        description:
          "Koleksi kecil untuk rumah yang hidup: tekstil, keramik, dan objek sehari-hari dengan material yang terasa jujur.",
        primaryCtaText: "Lihat Koleksi",
        primaryCtaUrl: "#koleksi",
        secondaryCtaText: "Cerita Luma",
        secondaryCtaUrl: "#cerita",
        imageUrl:
          "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Ruang keluarga hangat dengan kursi oranye dan tanaman besar",
        supportingText: "Dibuat dalam jumlah kecil. Dipilih untuk tinggal lebih lama.",
        imageBadgeText: "SEASONAL EDIT",
      },
      styles: { padding: "xl" },
    },
    {
      id: "fashion-products",
      componentType: "product-grid-basic",
      name: "Koleksi Musim Ini",
      props: {
        sectionId: "koleksi",
        sectionTitle: "Koleksi untuk memperlambat sedikit ritme rumah.",
        sectionSubtitle:
          "Empat objek yang nyaman dipakai berulang kali, dengan detail yang semakin terasa setelah tinggal bersama Anda.",
        productsJson: JSON.stringify([
          {
            id: "linen-throw",
            name: "Linen Throw / Clay",
            price: "Rp 485.000",
            tag: "Pilihan musim ini",
            description: "Tekstil linen lembut dengan tekstur yang membaik seiring dipakai.",
            actionText: "Lihat detail",
            imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "mug-set",
            name: "Mug Pagi / Oat",
            price: "Rp 245.000",
            tag: "Baru",
            description: "Sepasang mug keramik untuk kebiasaan kecil di meja makan.",
            actionText: "Lihat detail",
            imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "lamp",
            name: "Lampu Meja / Soft Brass",
            price: "Rp 795.000",
            tag: "Terbatas",
            description: "Cahaya yang hangat untuk menutup hari tanpa terburu-buru.",
            actionText: "Lihat detail",
            imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "vase",
            name: "Vase Terakota / No. 02",
            price: "Rp 315.000",
            tag: "Koleksi inti",
            description: "Bentuk sederhana untuk bunga, dahan, atau dibiarkan kosong.",
            actionText: "Lihat detail",
            imageUrl: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "fashion-promo",
      componentType: "cta-basic",
      name: "Ajakan Koleksi Baru",
      props: {
        title: "Datang lebih awal ke koleksi yang dibuat terbatas.",
        description: "Kami mengirim kabar saat warna, ukuran, atau karya kolaborasi baru siap dipesan.",
        buttonText: "Ikuti kabar Luma",
        buttonUrl: "#newsletter",
        secondaryText: "Kunjungi studio",
        secondaryUrl: "#kontak",
      },
      styles: { padding: "xl" },
    },
    {
      id: "fashion-gallery",
      componentType: "gallery-grid",
      name: "Lookbook Luma",
      props: {
        eyebrow: "Lookbook / tinggal bersama",
        title: "Luma di antara cahaya pagi, meja makan, dan sore yang tenang.",
        description: "Bukan benda yang menuntut perhatian—mereka hanya membuat ruang terasa sedikit lebih lengkap.",
        columns: "3",
        images: [
          { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85", alt: "Interior ruang makan dengan kursi kayu", title: "Ruang makan", caption: "Everyday objects" },
          { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=85", alt: "Kursi dan lampu di ruang tamu", title: "Cahaya sore", caption: "Quiet light" },
          { url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1000&q=85", alt: "Komposisi objek rumah di atas meja", title: "Meja kecil", caption: "Still life" },
          { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85", alt: "Interior rumah bernuansa netral", title: "Nada netral", caption: "Soft home" },
          { url: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=85", alt: "Detail kursi dan tekstil", title: "Tekstur sehari-hari", caption: "Material study" },
          { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=85", alt: "Sofa dan tanaman di ruang keluarga", title: "Ruang untuk pulang", caption: "Living slowly" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "fashion-stories",
      componentType: "testimonial-grid",
      name: "Cerita Pemilik Luma",
      props: {
        eyebrow: "Di rumah mereka",
        title: "Hal kecil yang membuat orang ingin pulang sedikit lebih cepat.",
        description: "Catatan dari orang-orang yang mengizinkan benda-benda Luma menjadi bagian dari rutinitasnya.",
        columns: "3",
        items: [
          { quote: "Mug ini selalu jadi yang pertama saya ambil setiap pagi. Rasanya kecil, tapi membuat ritualnya jauh lebih enak.", name: "Nisa Rahma", role: "Jakarta", initials: "NR" },
          { quote: "Kami suka karena ukurannya pas dan tidak ramai. Di rumah kecil, benda yang tenang justru terasa lebih penting.", name: "Ari & Kinan", role: "Bandung", initials: "AK" },
          { quote: "Tekstilnya semakin lembut setelah dicuci. Rasanya seperti benda yang memang dibuat untuk dipakai terus.", name: "Mira Sasmita", role: "Surabaya", initials: "MS" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "fashion-newsletter",
      componentType: "form-newsletter",
      name: "Newsletter Luma",
      props: {
        eyebrow: "Kabar dari studio",
        heading: "Masuk lebih dulu ke cerita koleksi berikutnya.",
        description: "Satu email saat karya baru, kolaborasi kecil, dan pilihan hadiah musiman dibuka.",
        placeholder: "Alamat email Anda",
        buttonText: "Ikuti kabar",
        note: "Tidak sering. Hanya saat ada sesuatu yang layak dibagikan.",
        successText: "Terima kasih—kabar dari studio akan kami kirimkan ke email Anda.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "fashion-footer",
      componentType: "footer-basic",
      name: "Footer Luma Objects",
      props: {
        brandName: "LUMA OBJECTS",
        tagline: "Benda-benda kecil untuk rumah yang benar-benar dihuni.",
        link1Text: "Koleksi",
        link1Url: "#koleksi",
        link2Text: "Cerita",
        link2Url: "#cerita",
        link3Text: "halo@lumaobjects.id",
        link3Url: "mailto:halo@lumaobjects.id",
        copyrightText: "© 2026 Luma Objects. Dibuat untuk dipakai lama.",
      },
      styles: { padding: "none" },
    },
  ];
}
