import type { RawTemplateNode } from "@/templates";

/** Hotel & resort — terinspirasi dari template "royal". */
export function createHotelLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "royal-nav",
      componentType: "navbar-glass",
      name: "Navigasi Royal Hotel",
      props: {
        logoText: "ROYAL",
        link1Text: "Kamar",
        link1Url: "#kamar",
        link2Text: "Fasilitas",
        link2Url: "#fasilitas",
        link3Text: "Paket",
        link3Url: "#paket",
        ctaText: "Pesan sekarang",
        ctaUrl: "#reservasi",
      },
      styles: { padding: "none" },
    },
    {
      id: "royal-hero",
      componentType: "hero-bg-image",
      name: "Hero Royal Hotel",
      props: {
        badgeText: "Hotel bintang lima di tepi Danau Toba",
        title: "Malam yang tenang, pemandangan yang tidak bisa dilupakan.",
        description:
          "Royal Toba berdiri di tepi kaldera dengan 120 kamar, spa tepi air, dan dapur yang mengangkat bahan pangan Sumatera Utara.",
        primaryCtaText: "Cek ketersediaan kamar",
        primaryCtaUrl: "#reservasi",
        secondaryCtaText: "Lihat fasilitas",
        secondaryCtaUrl: "#fasilitas",
        imageUrl:
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Kolam renang hotel menghadap danau saat senja",
        supportingText: "Check-in 14.00 · Check-out 12.00. Transportasi dari Bandara Silangit tersedia.",
        imageBadgeText: "DANAU TOBA",
        imageNoteLabel: "Kedatangan",
        imageNoteText: "80 menit dari Bandara Silangit, dengan jemputan gratis.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "royal-tentang",
      componentType: "about-basic",
      name: "Tentang Royal Toba",
      props: {
        sectionId: "tentang",
        eyebrow: "Tentang hotel",
        title: "Keramahan Batak dalam standar pelayanan bintang lima.",
        description:
          "Royal Toba dibangun tahun 2018 di atas lahan 2,4 hektare tepi Danau Toba. Kami memadukan arsitektur Batak modern, bahan lokal, dan pelayanan yang dilatih dari budaya asli masyarakat setempat — tamu bukan tamu, melainkan keluarga yang berkunjung.",
        imageUrl:
          "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=85",
        imageAlt: "Lobi hotel mewah dengan cahaya hangat",
        imageNoteLabel: "Sejarah singkat",
        imageNoteText: "Dibangun 2018 · 120 kamar · 140 karyawan lokal.",
        stat1Number: "120",
        stat1Label: "kamar dan suite",
        stat2Number: "2,4",
        stat2Label: "hektare lahan tepi danau",
        stat3Number: "98%",
        stat3Label: "tamu merekomendasikan kepada kerabat",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "royal-kamar",
      componentType: "gallery-grid",
      name: "Kamar & Suite",
      props: {
        sectionId: "kamar",
        eyebrow: "Kamar & suite",
        title: "Tiga tipe kamar, satu standar kenyamanan.",
        description: "Setiap kamar menghadap danau dengan balkon pribadi, kasur king size, dan perabotan dari kayu jati lokal.",
        columns: "3",
        images: [
          {
            url: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=85",
            title: "Deluxe Danau",
            caption: "38 m² · mulai Rp 1,8 jt/malam",
            alt: "Kamar hotel mewah dengan pemandangan danau",
          },
          {
            url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=85",
            title: "Suite Panorama",
            caption: "56 m² · mulai Rp 3,2 jt/malam",
            alt: "Suite hotel dengan ruang tamu terpisah",
          },
          {
            url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=85",
            title: "Villa Tepi Air",
            caption: "88 m² · mulai Rp 5,5 jt/malam",
            alt: "Villa tepi air dengan teras pribadi",
          },
          {
            url: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=85",
            title: "Kamar Mandi Marmer",
            caption: "Bathtub & shower terpisah",
            alt: "Kamar mandi marmer dengan bathtub",
          },
          {
            url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=1200&q=85",
            title: "Restoran & Bar",
            caption: "Sarapan prasmanan 06.00–10.30",
            alt: "Restoran hotel dengan meja kayu panjang",
          },
          {
            url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=85",
            title: "Spa Tepi Air",
            caption: "Buka 09.00–21.00",
            alt: "Ruang spa dengan lilin dan handuk putih",
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "royal-statistik",
      componentType: "stats-banner",
      name: "Statistik Royal Toba",
      props: {
        eyebrow: "Fasilitas & layanan",
        title: "Yang membuat malam Anda di sini terasa berbeda.",
        sectionBg: "primary",
        stats: [
          { value: "120", suffix: "", label: "kamar dan suite berhadapan danau" },
          { value: "3", suffix: "", label: "restoran & bar di dalam hotel" },
          { value: "24", suffix: " jam", label: "layanan kamar dan concierge" },
          { value: "500", suffix: "+", label: "tamu setiap minggu" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "royal-paket",
      componentType: "pricing-table",
      name: "Paket Menginap",
      props: {
        sectionId: "paket",
        eyebrow: "Paket menginap",
        title: "Pilih paket yang paling sesuai rencana Anda.",
        description: "Semua paket sudah termasuk sarapan untuk dua orang, akses spa pagi, dan transportasi dari bandara.",
        plans: [
          {
            id: "royal-romantis",
            name: "Akhir Pekan",
            price: "Rp 2,1 jt",
            period: "/malam",
            description: "Untuk pasangan yang ingin pelarian singkat dari kota.",
            features: ["Kamar Deluxe Danau", "Sarapan untuk dua", "Minuman selamat datang", "Check-out hingga 14.00"],
            buttonText: "Pilih paket",
            buttonUrl: "#reservasi",
            highlighted: false,
          },
          {
            id: "royal-keluarga",
            name: "Keluarga",
            price: "Rp 3,9 jt",
            period: "/malam",
            description: "Untuk keluarga dengan anak, termasuk fasilitas taman bermain.",
            features: ["Suite Panorama", "Sarapan untuk empat", "Kelas memasak anak", "Sewa sepeda gratis", "Layanan bayi & pengasuh"],
            buttonText: "Pilih paket",
            buttonUrl: "#reservasi",
            highlighted: true,
          },
          {
            id: "royal-liburan",
            name: "Libur Panjang",
            price: "Rp 4,8 jt",
            period: "/malam",
            description: "Untuk liburan 3 malam atau lebih dengan keuntungan paling banyak.",
            features: ["Villa Tepi Air", "Sarapan & makan malam", "Sesi spa 60 menit", "Tur desa budaya Batak", "Harga khusus 3 malam+"],
            buttonText: "Pilih paket",
            buttonUrl: "#reservasi",
            highlighted: false,
          },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "royal-testimoni",
      componentType: "testimonial-grid",
      name: "Ulasan Tamu",
      props: {
        sectionId: "ulasan",
        eyebrow: "Kata tamu",
        title: "Yang mereka ceritakan setelah pulang.",
        description: "Ulasan dari tamu yang menginap dalam enam bulan terakhir.",
        columns: "3",
        items: [
          {
            quote: "Pemandangan dari balkon tidak bisa dibeli dengan kamera apa pun. Pelayanannya hangat tanpa berlebihan.",
            name: "Intan Puspita",
            role: "Jakarta · menginap 2 malam",
            initials: "IP",
          },
          {
            quote: "Kelas memasak anak-anak jadi highlight liburan kami. Anak saya sampai minta kembali bulan depan.",
            name: "Budi Hartono",
            role: "Medan · keluarga 4 orang",
            initials: "BH",
          },
          {
            quote: "Kami datang untuk honeymoon. Staf tahu, dan menyiapkan kejutan kecil di kamar. Detail seperti ini langka.",
            name: "Rizky & Anisa",
            role: "Surabaya · paket akhir pekan",
            initials: "RA",
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "royal-reservasi",
      componentType: "form-contact",
      name: "Form Reservasi",
      props: {
        sectionId: "reservasi",
        eyebrow: "Reservasi",
        heading: "Pesan kamar atau paket liburan Anda.",
        subheading: "Isi nama, email, dan perkiraan tanggal. Tim reservasi kami konfirmasi dalam dua jam di jam kerja.",
        email: "reservasi@royaltoba.id",
        nameLabel: "Nama Anda",
        namePlaceholder: "Contoh: Intan Puspita",
        emailLabel: "Email",
        emailPlaceholder: "nama@email.com",
        messageLabel: "Tanggal, jumlah tamu, dan paket",
        messagePlaceholder: "Contoh: 12–14 Nov, 2 dewasa, paket akhir pekan",
        buttonText: "Kirim permintaan reservasi",
        note: "Uang muka 30% diperlukan untuk mengunci kamar. Bisa dibatalkan gratis hingga 7 hari sebelum menginap.",
        successText: "Permintaan reservasi diterima. Kami kirim konfirmasi ketersediaan ke email Anda.",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "royal-cta",
      componentType: "cta-basic",
      name: "Ajakan Menginap",
      props: {
        title: "Tempat tenang di tepi danau sedang menunggu Anda.",
        description: "Jl. Lingkar Toba No. 12, Parapat, Sumatera Utara. Reservasi telepon dibuka 24 jam.",
        buttonText: "Hubungi (0625) 411-222",
        buttonUrl: "tel:+62625411222",
        secondaryText: "Cek paket",
        secondaryUrl: "#paket",
      },
      styles: { padding: "xl" },
    },
    {
      id: "royal-footer",
      componentType: "footer-basic",
      name: "Footer Royal Toba",
      props: {
        brandName: "ROYAL",
        tagline: "Hotel bintang lima di tepi Danau Toba. Jl. Lingkar Toba No. 12, Parapat. Reservasi 24 jam.",
        link1Text: "Kamar",
        link1Url: "#kamar",
        link2Text: "Paket",
        link2Url: "#paket",
        link3Text: "(0625) 411-222",
        link3Url: "tel:+62625411222",
        copyrightText: "© 2026 Royal Toba Hotel & Resort.",
      },
      styles: { padding: "none" },
    },
    {
      id: "royal-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}