import type { RawTemplateNode } from "@/templates";

/** Menu kafe digital — terinspirasi dari template "website-menu-03". */
export function createKafeMenuNodes(): RawTemplateNode[] {
  return [
    {
      id: "kafe-nav",
      componentType: "navbar-minimal",
      name: "Navigasi Kafe Senja",
      props: {
        logoText: "kafe senja",
        link1Text: "Menu",
        link1Url: "#menu",
        link2Text: "Cerita",
        link2Url: "#cerita",
        link3Text: "Lokasi",
        link3Url: "#lokasi",
        ctaText: "Pesan meja",
        ctaUrl: "#lokasi",
      },
      styles: { padding: "none" },
    },
    {
      id: "kafe-hero",
      componentType: "hero-centered",
      name: "Hero Kafe Senja",
      props: {
        badgeText: "Kopi & kue buatan sendiri — dibuka sejak 2015",
        title: "Tempat mengurai hari dengan kopi yang dipanggang sendiri.",
        description:
          "Kafe Senja memanggang biji kopi dari Gayo dan Kintamani setiap minggu. Temukan tempat duduk dekat jendela, dan biarkan sore berjalan lebih lambat.",
        primaryCtaText: "Lihat menu",
        primaryCtaUrl: "#menu",
        secondaryCtaText: "Temukan kami",
        secondaryCtaUrl: "#lokasi",
        imageUrl:
          "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Cangkir kopi latte di atas meja kayu kafe",
        supportingText: "Wi-Fi cepat · colokan di setiap meja · ramah laptop.",
        imageBadgeText: "ROASTED IN-HOUSE",
        imageNoteLabel: "Barista kami",
        imageNoteText: "Dua barista bersertifikat dengan 300+ resep.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "kafe-menu",
      componentType: "product-grid-basic",
      name: "Menu Kafe Senja",
      props: {
        sectionId: "menu",
        sectionTitle: "Menu yang kami buat sendiri tiap pagi.",
        sectionSubtitle:
          "Kopi, teh, dan kue yang dipanggang di dapur kami. Harga sudah termasuk pajak.",
        productsJson: JSON.stringify([
          {
            id: "kafe-1",
            name: "Espresso Gayo",
            price: "Rp 28.000",
            tag: "Kopi",
            description: "Tunggal asal Gayo, profil cokelat dan karamel. Disajikan 30 ml.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kafe-2",
            name: "Kopi Susu Senja",
            price: "Rp 34.000",
            tag: "Andalan",
            description: "Espresso ganda dengan susu segar dan gula aren cair.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kafe-3",
            name: "Matcha Latte",
            price: "Rp 38.000",
            tag: "Tanpa kopi",
            description: "Matcha premium Jepang dengan susu oat atau susu segar.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kafe-4",
            name: "Kue Cokelat Lava",
            price: "Rp 42.000",
            tag: "Kue",
            description: "Cokelat 65% yang meleleh di tengah, dengan es krim vanila.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kafe-5",
            name: "Croissant Mentega",
            price: "Rp 25.000",
            tag: "Kue",
            description: "Panggang pagi hari, 27 lapis adonan mentega asli.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kafe-6",
            name: "Es Teh Leci",
            price: "Rp 22.000",
            tag: "Minuman",
            description: "Teh melati dingin dengan leci segar dan daun mint.",
            actionText: "Pesan",
            actionUrl: "#lokasi",
            imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "kafe-promo",
      componentType: "banner-promo",
      name: "Promo Happy Hour",
      props: {
        badge: "Setiap hari 15.00–17.00",
        heading: "Happy hour: kopi susu kedua diskon 30%.",
        description: "Untuk pembelian kopi susu pertama dengan harga normal. Berlaku untuk dine-in, tidak bisa digabung dengan promo lain.",
        ctaText: "Temukan kami",
        ctaUrl: "#lokasi",
      },
      styles: { padding: "xl" },
    },
    {
      id: "kafe-cerita",
      componentType: "social-proof",
      name: "Ulasan Kafe Senja",
      props: {
        sectionId: "cerita",
        rating: 5,
        ratingText: "4,8 dari 5",
        countText: "2.300+ ulasan Google",
        note: "Berdiri sejak 2015 di Jl. Gajah Mada, Yogyakarta. Ulasan datang dari pengunjung yang datang langsung, bukan dari tamu undangan.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "kafe-newsletter",
      componentType: "form-newsletter",
      name: "Info Menu Musiman",
      props: {
        eyebrow: "Menu musiman",
        heading: "Kabar dulu soal biji kopi dan kue baru.",
        description: "Berlangganan dan dapatkan info menu musiman serta undangan cupping sebulan sekali.",
        placeholder: "nama@email.com",
        buttonText: "Berlangganan",
        note: "Sekali sebulan, tanpa spam. 8.700 pembaca aktif.",
        successText: "Terima kasih! Email pertama soal menu musiman akan segera masuk.",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "kafe-cta",
      componentType: "cta-basic",
      name: "Lokasi & Jam Buka",
      props: {
        sectionId: "lokasi",
        title: "Mampir sebelum senja tiba.",
        description: "Jl. Gajah Mada No. 33, Yogyakarta. Buka setiap hari 08.00–22.00, dapur kue tutup 20.00.",
        buttonText: "Pesan meja",
        buttonUrl: "#lokasi",
        secondaryText: "Lihat menu",
        secondaryUrl: "#menu",
      },
      styles: { padding: "xl" },
    },
    {
      id: "kafe-footer",
      componentType: "footer-basic",
      name: "Footer Kafe Senja",
      props: {
        brandName: "kafe senja",
        tagline: "Kopi panggang sendiri, kue buatan dapur, dan sore yang lebih lambat. Jl. Gajah Mada No. 33, Yogyakarta.",
        link1Text: "Menu",
        link1Url: "#menu",
        link2Text: "Cerita",
        link2Url: "#cerita",
        link3Text: "(0274) 512-098",
        link3Url: "tel:+62274512098",
        copyrightText: "© 2026 Kafe Senja.",
      },
      styles: { padding: "none" },
    },
    {
      id: "kafe-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}