import type { RawTemplateNode } from "@/templates";

/** Portofolio one-page gelap — terinspirasi dari template "flameonepage". */
export function createPortofolioOnepageNodes(): RawTemplateNode[] {
  return [
    {
      id: "onepage-nav",
      componentType: "navbar-minimal",
      name: "Navigasi Portofolio",
      props: {
        logoText: "©",
        link1Text: "Karya",
        link1Url: "#karya",
        link2Text: "Tentang",
        link2Url: "#tentang",
        link3Text: "Proses",
        link3Url: "#proses",
        ctaText: "Hubungi saya",
        ctaUrl: "#kontak",
      },
      styles: { padding: "none" },
    },
    {
      id: "onepage-hero",
      componentType: "hero-centered",
      name: "Hero One-Page",
      props: {
        badgeText: "Desainer produk & pengembang antarmuka",
        title: "Merancang produk digital yang terasa jelas sejak detik pertama.",
        description:
          "Saya Bayu — desainer produk dengan 8 tahun pengalaman di startup dan studio. Fokus pada antarmuka yang jernih, keputusan yang bisa dijelaskan, dan detail yang terasa.",
        primaryCtaText: "Lihat karya pilihan",
        primaryCtaUrl: "#karya",
        secondaryCtaText: "Tentang saya",
        secondaryCtaUrl: "#tentang",
        imageUrl:
          "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Meja kerja desainer dengan sketsa antarmuka dan monitor",
        supportingText: "Tersedia untuk proyek freelance mulai November 2026.",
        imageBadgeText: "BAYU H.",
        imageNoteLabel: "Studio kecil saya",
        imageNoteText: "Berbasis di Bandung, bekerja untuk klien di 6 negara.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "onepage-karya",
      componentType: "gallery-grid",
      name: "Karya Pilihan",
      props: {
        sectionId: "karya",
        eyebrow: "Karya pilihan",
        title: "Enam proyek yang paling banyak saya pelajari.",
        description: "Dari aplikasi keuangan hingga platform komunitas — dipilih karena masalah desainnya menarik untuk diceritakan.",
        columns: "3",
        images: [
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85",
            title: "Tabungan — Aplikasi Keuangan",
            caption: "Desain produk · 2025",
            alt: "Dashboard aplikasi keuangan di layar laptop",
          },
          {
            url: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1200&q=85",
            title: "Kampus — Platform Komunitas",
            caption: "Desain & riset · 2025",
            alt: "Antarmuka platform komunitas di layar ponsel",
          },
          {
            url: "https://images.unsplash.com/photo-1541462608143-67571c6738dd?auto=format&fit=crop&w=1200&q=85",
            title: "Atlas — Sistem Desain",
            caption: "Sistem desain · 2024",
            alt: "Halaman komponen sistem desain",
          },
          {
            url: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?auto=format&fit=crop&w=1200&q=85",
            title: "Resep — Aplikasi Memasak",
            caption: "Desain produk · 2024",
            alt: "Antarmuka aplikasi resep dengan foto makanan",
          },
          {
            url: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=1200&q=85",
            title: "Arsip — Website Redaksi",
            caption: "Desain website · 2023",
            alt: "Tampilan website redaksi berita",
          },
          {
            url: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=85",
            title: "Jaga — Aplikasi Kesehatan",
            caption: "Desain produk · 2023",
            alt: "Antarmuka aplikasi kesehatan di ponsel",
          },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "onepage-tentang",
      componentType: "about-basic",
      name: "Tentang Bayu",
      props: {
        sectionId: "tentang",
        eyebrow: "Tentang",
        title: "Desainer yang juga bisa membaca kode.",
        description:
          "Latar belakang saya campuran: desain komunikasi visual dan pengembangan front-end. Saya percaya desainer yang memahami keterbatasan teknologi menghasilkan keputusan yang lebih jujur — dan prototipe yang lebih dekat dengan produk akhir.",
        imageUrl:
          "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1200&q=85",
        imageAlt: "Pekerjaan desain dan kode di layar laptop",
        imageNoteLabel: "Perangkat harian",
        imageNoteText: "Figma, VS Code, dan buku catatan yang selalu penuh.",
        stat1Number: "8",
        stat1Label: "tahun di desain produk",
        stat2Number: "23",
        stat2Label: "proyek diluncurkan",
        stat3Number: "6",
        stat3Label: "negara klien",
      },
      styles: { padding: "xl" },
    },
    {
      id: "onepage-proses",
      componentType: "process-steps",
      name: "Cara Bekerja",
      props: {
        sectionId: "proses",
        eyebrow: "Proses",
        heading: "Cara saya bekerja dari brief hingga peluncuran.",
        stepsJson: [
          { title: "Pahami masalah", description: "Wawancara pengguna, audit produk, dan diskusi dengan tim untuk menemukan masalah sebenarnya." },
          { title: "Rancang & uji", description: "Alur, wireframe, dan prototipe yang diuji ke pengguna nyata sebelum satu piksel dirapikan." },
          { title: "Rapikan & dokumentasikan", description: "Desain akhir, sistem komponen, dan dokumentasi yang mudah diteruskan ke tim engineering." },
          { title: "Pantau peluncuran", description: "Pendampingan implementasi, review antarmuka, dan iterasi berdasarkan data pasca rilis." },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "onepage-cta",
      componentType: "cta-basic",
      name: "Ajakan Kolaborasi",
      props: {
        title: "Membangun sesuatu yang perlu desain jernih?",
        description: "Kirim detail proyek Anda — saya balas dalam dua hari kerja dengan pendapat jujur tentang peluangnya.",
        buttonText: "kirim@bayuh.dev",
        buttonUrl: "mailto:kirim@bayuh.dev",
        secondaryText: "Lihat karya lagi",
        secondaryUrl: "#karya",
      },
      styles: { padding: "xl" },
    },
    {
      id: "onepage-footer",
      componentType: "footer-basic",
      name: "Footer Portofolio",
      props: {
        brandName: "Bayu H.",
        tagline: "Desainer produk & pengembang antarmuka. Bandung, Indonesia. Siap membantu dari mana pun Anda berada.",
        link1Text: "Karya",
        link1Url: "#karya",
        link2Text: "Tentang",
        link2Url: "#tentang",
        link3Text: "kirim@bayuh.dev",
        link3Url: "mailto:kirim@bayuh.dev",
        copyrightText: "© 2026 Bayu Hidayat.",
      },
      styles: { padding: "none" },
    },
    {
      id: "onepage-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}