import type { RawTemplateNode } from "@/templates";

/** Cluster perumahan dengan daftar unit, galeri, testimoni pembeli, dan form konsultasi KPR. */
export function createPropertiLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "properti-nav",
      componentType: "navbar-minimal",
      name: "Navigasi Taman Asri",
      props: {
        logoText: "Taman Asri",
        link1Text: "Unit",
        link1Url: "#unit",
        link2Text: "Lokasi",
        link2Url: "#lokasi",
        link3Text: "Kontak",
        link3Url: "#kunjungan",
        ctaText: "Jadwalkan kunjungan",
        ctaUrl: "#kunjungan",
      },
      styles: { padding: "none" },
    },
    {
      id: "properti-hero",
      componentType: "hero-centered",
      name: "Hero Taman Asri",
      props: {
        badgeText: "Cluster Taman Asri, Bekasi Selatan",
        title: "Rumah tapak bersertifikat mulai Rp 850 juta di Bekasi Selatan.",
        description:
          "Angsuran pertama mulai Rp 4,9 juta per bulan dengan DP 0 untuk program tertentu. Lingkungan berpagar, enam menit dari Gerbang Tol JORR Pekayon, dan 1,2 km dari sekolah negeri.",
        primaryCtaText: "Jadwalkan kunjungan",
        primaryCtaUrl: "#kunjungan",
        secondaryCtaText: "Lihat denah",
        secondaryCtaUrl: "#unit",
        imageUrl:
          "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Rumah tapak modern dua lantai dengan halaman di kawasan perumahan",
        supportingText: "Show unit buka Sabtu–Minggu 09.00–17.00",
        imageBadgeText: "MULAI DARI Rp 850 JT",
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-stats",
      componentType: "stats-banner",
      name: "Statistik Taman Asri",
      props: {
        eyebrow: "Angka penjualan per November 2026",
        title: "Kawasan yang tinggal sedikit kursinya.",
        sectionBg: "primary",
        stats: [
          { value: "118", suffix: " unit", label: "dari 140 unit sudah terjual" },
          { value: "6×12", suffix: " m", label: "luas kavling tersisa" },
          { value: "14", suffix: "", label: "fasilitas umum & olahraga" },
          { value: "0", suffix: "%", label: "DP untuk program tertentu" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-unit",
      componentType: "product-grid-basic",
      name: "Unit Tersedia",
      props: {
        sectionId: "unit",
        sectionTitle: "Enam tipe rumah yang masih bisa dipesan.",
        sectionSubtitle:
          "Semua unit SHM siap AJB dan dibangun oleh kontraktor berizin. Denah lengkap dibagikan saat kunjungan ke show unit.",
        productsJson: JSON.stringify([
          {
            id: "tipe-36",
            name: "Tipe 36/72",
            price: "Rp 850 juta",
            tag: "Tersisa 12 unit",
            description: "2 kamar, 1 lantai, kavling 6×12 meter.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tipe-45",
            name: "Tipe 45/84",
            price: "Rp 985 juta",
            tag: "Tersisa 7 unit",
            description: "2 kamar, 1 lantai, taman depan 2×4 meter.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tipe-54",
            name: "Tipe 54/96",
            price: "Rp 1,15 miliar",
            tag: "Terlaris",
            description: "3 kamar, 2 lantai, garasi satu mobil.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tipe-60",
            name: "Tipe 60/108",
            price: "Rp 1,28 miliar",
            tag: "Tersisa 4 unit",
            description: "3 kamar, 2 lantai, SHM siap AJB.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tipe-70",
            name: "Tipe 70/120",
            price: "Rp 1,45 miliar",
            tag: "Baru rilis",
            description: "4 kamar, 2 lantai, menghadap taman cluster.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tipe-90",
            name: "Tipe 90/150",
            price: "Rp 1,9 miliar",
            tag: "Unit contoh",
            description: "4 kamar + 1 kamar pembantu, halaman 150 m², akses gerbang utama.",
            actionText: "Lihat denah",
            actionUrl: "#kunjungan",
            imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "properti-about",
      componentType: "about-basic",
      name: "Lokasi & Fasilitas Taman Asri",
      props: {
        sectionId: "lokasi",
        eyebrow: "Lokasi & fasilitas",
        title: "Kawasan yang sudah jadi, bukan hanya janji di brosur.",
        description:
          "Cluster Taman Asri berada di Pekayon, Bekasi Selatan—enam menit ke Gerbang Tol JORR Pekayon dan sepuluh menit ke Stasiun LRT Jatimulya. Fasilitas yang sudah beroperasi: pos keamanan 24 jam, kolam renang, lapangan futsal, dan taman bermain anak seluas 1.800 m².",
        imageUrl:
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=85",
        imageAlt: "Eksterior rumah modern dengan halaman dan jalan perumahan yang rapi",
        imageNoteLabel: "Fasilitas",
        imageNoteText: "Kolam renang, futsal, dan pos satpam beroperasi sejak 2023.",
        stat1Number: "6",
        stat1Label: "menit ke Gerbang Tol JORR Pekayon",
        stat2Number: "1.800",
        stat2Label: "m² taman bermain anak",
        stat3Number: "24",
        stat3Label: "jam keamanan dengan satu pintu gerbang",
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-galeri",
      componentType: "gallery-grid",
      name: "Galeri Foto Unit",
      props: {
        eyebrow: "Galeri unit",
        title: "Lihat unit contoh seperti tamu yang datang ke show unit.",
        description: "Foto diambil dari unit contoh Tipe 54 dan area umum cluster tanpa efek berlebihan.",
        columns: "3",
        images: [
          { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85", alt: "Ruang keluarga unit contoh dengan sofa", title: "Ruang keluarga", caption: "Tipe 54" },
          { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85", alt: "Dapur dengan kitchen set di unit contoh", title: "Dapur & kitchen set", caption: "Tipe 54" },
          { url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=85", alt: "Kamar tidur utama dengan jendela besar", title: "Kamar utama", caption: "Tipe 54" },
          { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1000&q=85", alt: "Taman bermain anak di tengah cluster", title: "Taman bermain", caption: "Area umum" },
          { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=85", alt: "Fasad rumah di cluster Taman Asri", title: "Fasad Tipe 60", caption: "Tipe 60" },
          { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=85", alt: "Rumah dengan halaman luas di sore hari", title: "Halaman Tipe 90", caption: "Tipe 90" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "properti-testimoni",
      componentType: "testimonial-grid",
      name: "Testimoni Pembeli",
      props: {
        eyebrow: "Kata pembeli",
        title: "Mereka yang sudah tinggal, bukan hanya menandatangani kontrak.",
        description: "Ulasan kami kumpulkan dari wawancara langsung setelah serah terima kunci.",
        columns: "3",
        items: [
          { quote: "Proses AJB selesai tiga minggu. Semua fasilitas yang dijanjikan ternyata sudah jadi saat kami pindah.", name: "Dedi Kurniawan", role: "Pembeli Tipe 54", initials: "DK" },
          { quote: "Tim pemasaran menjelaskan rincian angsuran sampai biaya per meter—tidak ada biaya tersembunyi.", name: "Fitri Handayani", role: "Pembeli Tipe 36", initials: "FH" },
          { quote: "Pagar keliling dan satu pintu gerbang membuat anak saya leluasa bermain di taman.", name: "Andra Wijaya", role: "Pembeli Tipe 70", initials: "AW" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-kpr",
      componentType: "form-contact",
      name: "Form Konsultasi KPR",
      props: {
        eyebrow: "Konsultasi KPR",
        heading: "Simulasi angsuran gratis tanpa biaya.",
        subheading: "Kami bekerja sama dengan tujuh bank—BTN, BRI, Mandiri, BCA, dan lainnya. Isi data, simulasi dikirim dalam 1×24 jam.",
        email: "marketing@tamanasri.id",
        nameLabel: "Nama Anda",
        namePlaceholder: "Contoh: Budi Santoso",
        emailLabel: "Email",
        emailPlaceholder: "nama@email.com",
        messageLabel: "Tipe unit & DP yang diinginkan",
        messagePlaceholder: "Contoh: Tipe 54/96 dengan DP 10%",
        buttonText: "Minta simulasi KPR",
        note: "Data hanya digunakan untuk simulasi pembiayaan, tidak dibagikan ke pihak lain.",
        successText: "Terima kasih—simulasi KPR akan dikirim ke email Anda dalam 1×24 jam.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-faq",
      componentType: "faq-accordion",
      name: "FAQ Taman Asri",
      props: {
        eyebrow: "Pertanyaan umum",
        title: "KPR, sertifikat, dan angsuran.",
        description: "Belum terjawab? Tanyakan langsung ke tim marketing di (021) 8895-1720.",
        items: [
          { question: "Apakah unit sudah bersertifikat?", answer: "Semua unit SHM atas nama pembeli dan siap AJB. Tidak ada sistem girik atau letter C." },
          { question: "Berapa angsuran untuk Tipe 36/72?", answer: "Dengan DP 10% dan tenor 20 tahun, simulasi angsuran sekitar Rp 6,2 juta per bulan. Angka pasti menyesuaikan suku bunga bank yang dipilih." },
          { question: "Apakah bisa memakai KPR tanpa DP?", answer: "Bisa untuk program tertentu bekerja sama dengan BTN dan BRI, dengan syarat pendapatan dan rekam kredit disetujui bank." },
          { question: "Kapan unit bisa dihuni?", answer: "Tipe yang tersisa dibangun secara bertahap. Estimasi serah terima kunci 6–9 bulan setelah akad, tertulis di perjanjian jual beli." },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "properti-cta",
      componentType: "cta-basic",
      name: "Ajakan Kunjungan Taman Asri",
      props: {
        title: "Jadwalkan kunjungan akhir pekan ini.",
        description: "Show unit di Jl. Raya Pekayon No. 9, Bekasi Selatan, buka Sabtu–Minggu 09.00–17.00. Kunjungan wajib didaftarkan lebih dulu.",
        buttonText: "Jadwalkan kunjungan",
        buttonUrl: "#kunjungan",
        secondaryText: "Lihat denah",
        secondaryUrl: "#unit",
      },
      styles: { padding: "xl" },
    },
    {
      id: "properti-footer",
      componentType: "footer-basic",
      name: "Footer Taman Asri",
      props: {
        brandName: "TAMAN ASRI",
        tagline: "Rumah tapak bersertifikat di Bekasi Selatan, mulai Rp 850 juta. Dikembangkan Graha Andalan Property.",
        link1Text: "Unit",
        link1Url: "#unit",
        link2Text: "Kunjungi",
        link2Url: "#kunjungan",
        link3Text: "(021) 8895-1720",
        link3Url: "tel:+622188951720",
        copyrightText: "© 2026 Cluster Taman Asri · Graha Andalan Property.",
      },
      styles: { padding: "none" },
    },
    {
      id: "properti-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}
