import type { RawTemplateNode } from "@/templates";

/** Restoran modern — terinspirasi dari template "tasty-master". */
export function createRestoranModernNodes(): RawTemplateNode[] {
  return [
    {
      id: "tasty-nav",
      componentType: "navbar-centered",
      name: "Navigasi Rumah Kayu",
      props: {
        logoText: "RUMAH KAYU",
        link1Text: "Beranda",
        link1Url: "#",
        link2Text: "Tentang",
        link2Url: "#tentang",
        link3Text: "Menu",
        link3Url: "#menu",
        link4Text: "Reservasi",
        link4Url: "#reservasi",
        ctaText: "Pesan meja",
        ctaUrl: "#reservasi",
      },
      styles: { padding: "none" },
    },
    {
      id: "tasty-hero",
      componentType: "hero-bg-image",
      name: "Hero Rumah Kayu",
      props: {
        badgeText: "Masakan modern dengan bahan lokal — Magelang",
        title: "Api, kayu, dan bahan yang datang tiap pagi.",
        description:
          "Rumah Kayu memasak dengan perapian kayu dan bahan dari 12 petani lokal. Menu berubah mengikuti musim — apa yang tersedia hari ini menentukan apa yang kami masak.",
        primaryCtaText: "Lihat menu hari ini",
        primaryCtaUrl: "#menu",
        secondaryCtaText: "Reservasi meja",
        secondaryCtaUrl: "#reservasi",
        imageUrl:
          "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Meja restoran elegan dengan pencahayaan hangat",
        supportingText: "Buka Rabu–Minggu, 17.00–23.00. Dapur tutup 22.00.",
        imageBadgeText: "SINCE 2019",
        imageNoteLabel: "Jam buka",
        imageNoteText: "Rabu–Minggu 17.00–23.00 · Tutup Senin & Selasa.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "tasty-tentang",
      componentType: "about-basic",
      name: "Tentang Rumah Kayu",
      props: {
        sectionId: "tentang",
        eyebrow: "Cerita kami",
        title: "Dapur yang terbuka, bahan yang bisa dilacak.",
        description:
          "Rumah Kayu dibuka tahun 2019 oleh chef Arif dan istrinya, Maya, di sebuah rumah joglo tua. Kami memasak dengan api kayu, merokok daging sendiri, dan membeli sayur langsung dari petani di lereng Gunung Merapi. Menu berganti tiap musim — dan itu bagian yang membuat kami terus datang ke dapur dengan senang.",
        imageUrl:
          "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=85",
        imageAlt: "Koki menyiapkan hidangan di dapur terbuka restoran",
        imageNoteLabel: "Dapur kami",
        imageNoteText: "Perapian kayu menyala setiap hari sejak 2019.",
        stat1Number: "12",
        stat1Label: "petani dan peternak lokal",
        stat2Number: "7",
        stat2Label: "menu yang berubah tiap musim",
        stat3Number: "40",
        stat3Label: "kursi di ruang makan utama",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "tasty-menu",
      componentType: "product-grid-basic",
      name: "Menu Musim Ini",
      props: {
        sectionId: "menu",
        sectionTitle: "Menu yang sedang berjalan musim ini.",
        sectionSubtitle:
          "Enam hidangan dari dapur kami. Harga sudah termasuk pajak; hidangan bisa dine-in maupun dibawa pulang.",
        productsJson: JSON.stringify([
          {
            id: "tasty-1",
            name: "Beef Short Rib Asap",
            price: "Rp 185.000",
            tag: "Andalan",
            description: "Iga sapi diasap 12 jam, disajikan dengan jus merah dan kentang panggang.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tasty-2",
            name: "Ikan Kakap Bakar",
            price: "Rp 165.000",
            tag: "Musiman",
            description: "Kakap utuh dibakar di atas api kayu dengan sambal matah dan jeruk nipis.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tasty-3",
            name: "Pasta Truffle Jamur",
            price: "Rp 120.000",
            tag: "Vegetarian",
            description: "Pasta homemade dengan jamur merang, truffle lokal, dan keju parmesan.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tasty-4",
            name: "Ayam Betutu Kayu",
            price: "Rp 140.000",
            tag: "Asap kayu",
            description: "Ayam kampung utuh dibungkus daun, dimasak perlahan 8 jam di atas arang.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tasty-5",
            name: "Salad Kebun",
            price: "Rp 85.000",
            tag: "Segar",
            description: "Sayur kebun lokal, bunga edible, dan vinaigrette jeruk bali.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "tasty-6",
            name: "Kue Lumpur Cokelat",
            price: "Rp 75.000",
            tag: "Penutup",
            description: "Cokelat 70% dengan es krim kelapa muda dan kacang mete karamel.",
            actionText: "Pesan meja",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl" },
    },
    {
      id: "tasty-suasana",
      componentType: "gallery-grid",
      name: "Suasana Rumah Kayu",
      props: {
        eyebrow: "Suasana",
        title: "Ruang makan yang terasa seperti rumah besar.",
        description: "Joglo tua, meja kayu, dan lampu yang bisa diatur — dari makan keluarga hingga perayaan.",
        columns: "3",
        images: [
          {
            url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=85",
            title: "Ruang makan utama",
            caption: "40 kursi · pencahayaan hangat",
            alt: "Ruang makan restoran dengan meja kayu panjang",
          },
          {
            url: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=1200&q=85",
            title: "Teras taman",
            caption: "12 kursi · view kebun",
            alt: "Teras restoran menghadap taman",
          },
          {
            url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=85",
            title: "Bar minuman",
            caption: "Koktail & kopi lokal",
            alt: "Bar restoran dengan rak botol",
          },
          {
            url: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?auto=format&fit=crop&w=1200&q=85",
            title: "Dapur terbuka",
            caption: "Perapian kayu di depan tamu",
            alt: "Dapur terbuka dengan perapian kayu",
          },
          {
            url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=85",
            title: "Ruang privat",
            caption: "8–12 orang · untuk perayaan",
            alt: "Ruang privat restoran dengan meja panjang",
          },
          {
            url: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=85",
            title: "Taman depan",
            caption: "Area tunggu dengan kopi gratis",
            alt: "Taman depan restoran saat senja",
          },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "tasty-ulasan",
      componentType: "testimonial-grid",
      name: "Ulasan Tamu",
      props: {
        eyebrow: "Kata tamu",
        title: "Alasan mereka kembali.",
        description: "Ulasan dari tamu yang makan di Rumah Kayu dalam enam bulan terakhir.",
        columns: "3",
        items: [
          {
            quote: "Iga asapnya keluar dari tulang, dan sausnya membuat saya minta roti tambahan. Menu musiman benar-benar beda.",
            name: "Maya Anggraini",
            role: "Magelang · tamu rutin",
            initials: "MA",
          },
          {
            quote: "Kami pesan ruang privat untuk ulang tahun ibu. Dapur bahkan menyesuaikan menu untuk tamu vegetarian kami.",
            name: "Hendra Wijaya",
            role: "Yogyakarta · perayaan keluarga",
            initials: "HW",
          },
          {
            quote: "Bahan lokal yang diolah serius. Tempatnya hangat, pelayanannya tahu kapan harus hadir.",
            name: "Sinta Dewi",
            role: "Semarang · pertama kali datang",
            initials: "SD",
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "tasty-reservasi",
      componentType: "form-contact",
      name: "Form Reservasi Meja",
      props: {
        sectionId: "reservasi",
        eyebrow: "Reservasi",
        heading: "Pesan meja untuk makan malam yang tenang.",
        subheading: "Isi nama, email, jumlah tamu, dan tanggal. Kami konfirmasi maksimal tiga jam sebelum jam buka.",
        email: "meja@rumahkayu.id",
        nameLabel: "Nama Anda",
        namePlaceholder: "Contoh: Hendra Wijaya",
        emailLabel: "Email",
        emailPlaceholder: "nama@email.com",
        messageLabel: "Jumlah tamu, tanggal, dan catatan",
        messagePlaceholder: "Contoh: 6 orang, Sabtu 19.00, meja dekat jendela",
        buttonText: "Kirim permintaan meja",
        note: "Meja rombongan 10+ orang perlu pesan minimal dua hari sebelumnya.",
        successText: "Permintaan meja diterima. Konfirmasi ketersediaan akan kami kirim ke email Anda.",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "tasty-footer",
      componentType: "footer-basic",
      name: "Footer Rumah Kayu",
      props: {
        brandName: "RUMAH KAYU",
        tagline: "Masakan api kayu dengan bahan lokal. Jl. Magelang–Yogyakarta KM 7, Magelang. Buka Rabu–Minggu 17.00–23.00.",
        link1Text: "Menu",
        link1Url: "#menu",
        link2Text: "Reservasi",
        link2Url: "#reservasi",
        link3Text: "(0293) 315-890",
        link3Url: "tel:+62293315890",
        copyrightText: "© 2026 Rumah Kayu Restoran.",
      },
      styles: { padding: "none" },
    },
    {
      id: "tasty-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}