import type { RawTemplateNode } from "@/templates";

/** Warung makan Nusantara dengan menu andalan, ulasan, dan form reservasi meja. */
export function createRestoranLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "restoran-nav",
      componentType: "navbar-centered",
      name: "Navigasi Selera Nusantara",
      props: {
        logoText: "SELERA NUSANTARA",
        link1Text: "Beranda",
        link1Url: "#",
        link2Text: "Menu",
        link2Url: "#menu",
        link3Text: "Cerita dapur",
        link3Url: "#tentang",
        link4Text: "Reservasi",
        link4Url: "#reservasi",
        ctaText: "Pesan meja",
        ctaUrl: "#reservasi",
      },
      styles: { padding: "none" },
    },
    {
      id: "restoran-hero",
      componentType: "hero-split",
      name: "Hero Selera Nusantara",
      props: {
        badgeText: "Buka setiap hari 10.00–22.00",
        title: "Masakan rumah Nusantara, dari dapur kecil di Kota Lama.",
        description:
          "Nasi goreng kampung, rendang sapi, dan sate ayam yang dimasak setelah pesanan masuk. Tempat makan keluarga dengan 80 kursi di kawasan Kota Lama Semarang.",
        primaryCtaText: "Lihat menu",
        primaryCtaUrl: "#menu",
        secondaryCtaText: "Pesan meja",
        secondaryCtaUrl: "#reservasi",
        imageUrl:
          "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Meja makan kayu dengan masakan rumahan di restoran Kota Lama",
        supportingText: "Bumbu diulek pagi-pagi, dimasak saat Anda memesan.",
        imageBadgeText: "KOTA LAMA",
        imageNoteLabel: "Dapur kami",
        imageNoteText: "Sejak 2009 · 80 kursi · 600 porsi sehari.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "restoran-about",
      componentType: "about-basic",
      name: "Cerita Dapur Selera Nusantara",
      props: {
        sectionId: "tentang",
        eyebrow: "Cerita dapur",
        title: "Dapur yang bermula dari rumah Bu Siti di kampung.",
        description:
          "Selera Nusantara berdiri tahun 2009 dari dapur rumah Bu Siti di Semarang. Resep rendang dan sambal bawang masih memakai takaran yang sama sejak awal. Kami memasak setiap porsi setelah pesanan masuk—tidak ada yang dipanaskan ulang dari kemarin.",
        imageUrl:
          "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=85",
        imageAlt: "Koki menyiapkan masakan di dapur terbuka restoran",
        imageNoteLabel: "Dapur kami",
        imageNoteText: "Bumbu diulek setiap pagi sebelum jam 10.00.",
        stat1Number: "17",
        stat1Label: "tahun memasak dengan resep yang sama",
        stat2Number: "30",
        stat2Label: "menu masakan dan minuman",
        stat3Number: "80",
        stat3Label: "kursi untuk keluarga dan rombongan",
      },
      styles: { padding: "xl" },
    },
    {
      id: "restoran-menu",
      componentType: "product-grid-basic",
      name: "Menu Andalan",
      props: {
        sectionId: "menu",
        sectionTitle: "Menu andalan yang paling sering diulang pelanggan.",
        sectionSubtitle:
          "Enam menu yang paling banyak keluar dari dapur setiap harinya. Harga sudah termasuk pajak dan bisa dine-in maupun dibawa pulang.",
        productsJson: JSON.stringify([
          {
            id: "nasi-goreng-kampung",
            name: "Nasi Goreng Kampung",
            price: "Rp 35.000",
            tag: "Menu andalan",
            description: "Nasi goreng dengan sambal bawang, telur mata sapi, dan kerupuk.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "rendang-sapi",
            name: "Rendang Sapi",
            price: "Rp 48.000",
            tag: "Masak 4 jam",
            description: "Daging sapi dimasak santan selama 4 jam hingga kering berbumbu.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "gado-gado",
            name: "Gado-Gado",
            price: "Rp 32.000",
            tag: "Sayur segar",
            description: "Sayur rebus, tahu tempe, lontong, dan bumbu kacang diulek sendiri.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "sate-ayam",
            name: "Sate Ayam",
            price: "Rp 38.000",
            tag: "Bakar arang",
            description: "Sepuluh tusuk sate ayam dengan bumbu kacang dan lontong.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "es-cendol",
            name: "Es Cendol",
            price: "Rp 18.000",
            tag: "Minuman",
            description: "Cendol gula aren dari daun pandan dengan santan segar.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "kopi-susu",
            name: "Kopi Susu",
            price: "Rp 20.000",
            tag: "Minuman",
            description: "Espresso dengan susu murni dan gula aren cair.",
            actionText: "Pesan",
            actionUrl: "#reservasi",
            imageUrl: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "restoran-stats",
      componentType: "stats-banner",
      name: "Statistik Selera Nusantara",
      props: {
        eyebrow: "Dapur yang tidak pernah berhenti",
        title: "Angka yang kami hitung sendiri dari catatan dapur.",
        sectionBg: "primary",
        stats: [
          { value: "600", suffix: " porsi", label: "nasi goreng terjual setiap hari" },
          { value: "2009", suffix: "", label: "tahun dapur pertama dibuka" },
          { value: "30", suffix: "", label: "menu masakan dan minuman" },
          { value: "4,7", suffix: " / 5", label: "rating dari 1.900 ulasan Google" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "restoran-ulasan",
      componentType: "social-proof",
      name: "Ulasan Google Selera Nusantara",
      props: {
        rating: 5,
        ratingText: "4,7 dari 5",
        countText: "1.900+ ulasan Google",
        note: "Berdiri sejak 2009 di Kota Lama Semarang. Ulasan datang dari pengunjung yang makan langsung, bukan dari tamu undangan.",
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "restoran-reservasi",
      componentType: "form-contact",
      name: "Form Reservasi Meja",
      props: {
        eyebrow: "Reservasi",
        heading: "Pesan meja untuk keluarga atau rombongan kantor.",
        subheading: "Isi nama, email, dan jumlah tamu. Kami konfirmasi paling lambat satu jam sebelum jam tutup pada hari yang sama.",
        email: "meja@seleranusantara.id",
        nameLabel: "Nama Anda",
        namePlaceholder: "Contoh: Bu Sari",
        emailLabel: "Email",
        emailPlaceholder: "nama@email.com",
        messageLabel: "Jumlah tamu, tanggal, dan jam",
        messagePlaceholder: "Contoh: 12 orang, Sabtu 20.00",
        buttonText: "Kirim permintaan meja",
        note: "Meja rombongan hingga 40 orang perlu pesan minimal satu hari sebelumnya.",
        successText: "Permintaan meja diterima. Kami akan mengirim konfirmasi ke email Anda.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "restoran-cta",
      componentType: "cta-basic",
      name: "Ajakan Makan di Selera Nusantara",
      props: {
        title: "Bawa keluarga makan di tempat yang memasak dengan sabar.",
        description: "Terletak di Jl. Letjen Suprapto No. 21, Kota Lama Semarang. Parkir luas dan area ramah anak tersedia.",
        buttonText: "Pesan meja",
        buttonUrl: "#reservasi",
        secondaryText: "Lihat menu",
        secondaryUrl: "#menu",
      },
      styles: { padding: "xl" },
    },
    {
      id: "restoran-footer",
      componentType: "footer-basic",
      name: "Footer Selera Nusantara",
      props: {
        brandName: "SELERA NUSANTARA",
        tagline: "Masakan rumahan Nusantara di kawasan Kota Lama, Semarang. Buka setiap hari 10.00–22.00.",
        link1Text: "Menu",
        link1Url: "#menu",
        link2Text: "Reservasi",
        link2Url: "#reservasi",
        link3Text: "(024) 356-1982",
        link3Url: "tel:+62243561982",
        copyrightText: "© 2026 Warung Selera Nusantara.",
      },
      styles: { padding: "none" },
    },
    {
      id: "restoran-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}
