import type { RawTemplateNode } from "@/templates";

/** Product-led startup landing with a real feature/pricing hierarchy. */
export function createStartupLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "startup-nav",
      componentType: "navbar-glass",
      name: "Navigasi Orbitly",
      props: {
        logoText: "orbitly",
        link1Text: "Fitur",
        link1Url: "#fitur",
        link2Text: "Harga",
        link2Url: "#harga",
        link3Text: "Cerita pelanggan",
        link3Url: "#cerita",
        ctaText: "Coba gratis",
        ctaUrl: "#mulai",
      },
      styles: { padding: "none" },
    },
    {
      id: "startup-hero",
      componentType: "hero-centered",
      name: "Hero Orbitly",
      props: {
        badgeText: "Workspace untuk tim yang bergerak cepat",
        title: "Ritme kerja yang lebih jernih, tanpa menambah rapat.",
        description:
          "Orbitly menyatukan tugas, keputusan, dan pembaruan proyek agar seluruh tim selalu tahu apa yang paling penting hari ini.",
        primaryCtaText: "Mulai 14 hari gratis",
        primaryCtaUrl: "#mulai",
        secondaryCtaText: "Lihat cara kerja",
        secondaryCtaUrl: "#fitur",
        imageUrl:
          "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Tim produk berkolaborasi di depan dashboard proyek",
        supportingText: "Dipakai tim produk, operasi, dan layanan pelanggan setiap hari.",
        imageBadgeText: "LIVE WORKSPACE",
      },
      styles: { padding: "xl" },
    },
    {
      id: "startup-feature-grid",
      componentType: "grid-container",
      name: "Fitur Utama",
      props: { columns: "3", gap: "md" },
      styles: { padding: "xl", background: "muted" },
      children: [
        {
          id: "startup-feature-1",
          componentType: "card-feature",
          name: "Fitur Fokus Harian",
          props: {
            icon: "sparkles",
            eyebrow: "Fokus hari ini",
            title: "Semua orang melihat prioritas yang sama.",
            description: "Ringkas pekerjaan yang benar-benar perlu bergerak tanpa menyembunyikan konteks penting.",
            linkText: "Lihat workspace",
            linkUrl: "#fitur",
          },
        },
        {
          id: "startup-feature-2",
          componentType: "card-feature",
          name: "Fitur Keputusan",
          props: {
            icon: "layers",
            eyebrow: "Keputusan tertata",
            title: "Catat alasan, bukan hanya hasil akhirnya.",
            description: "Setiap keputusan proyek tetap bisa ditemukan saat tim membutuhkan konteksnya kembali.",
            linkText: "Lihat alur kerja",
            linkUrl: "#fitur",
          },
        },
        {
          id: "startup-feature-3",
          componentType: "card-feature",
          name: "Fitur Progress",
          props: {
            icon: "chart",
            eyebrow: "Progress nyata",
            title: "Pembaruan yang tidak membutuhkan presentasi.",
            description: "Status proyek diperbarui di tempat kerja berlangsung, bukan dikejar di akhir minggu.",
            linkText: "Lihat contoh",
            linkUrl: "#cerita",
          },
        },
      ],
    },
    {
      id: "startup-stats",
      componentType: "stats-banner",
      name: "Statistik Orbitly",
      props: {
        eyebrow: "Tim yang bekerja lebih tenang",
        title: "Lebih sedikit mengejar kabar. Lebih banyak menyelesaikan pekerjaan.",
        sectionBg: "primary",
        stats: [
          { value: "34", suffix: "%", label: "waktu koordinasi berkurang" },
          { value: "2,4", suffix: "x", label: "update proyek lebih cepat" },
          { value: "11", suffix: " jam", label: "rapat rutin dihemat tiap minggu" },
          { value: "98", suffix: "%", label: "tim tetap menggunakannya setelah 3 bulan" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "startup-pricing",
      componentType: "pricing-table",
      name: "Harga Orbitly",
      props: {
        eyebrow: "Harga sederhana",
        title: "Mulai kecil, lalu bertumbuh saat tim Anda siap.",
        description: "Tidak ada biaya tersembunyi. Pilih paket yang paling nyaman untuk cara kerja tim saat ini.",
        plans: [
          {
            name: "Start",
            price: "Rp0",
            period: "/selamanya",
            description: "Untuk tim kecil yang ingin menyatukan pekerjaan inti.",
            features: ["Hingga 5 anggota", "3 proyek aktif", "Ringkasan mingguan"],
            buttonText: "Mulai gratis",
            buttonUrl: "#mulai",
            highlighted: false,
          },
          {
            name: "Flow",
            price: "Rp89rb",
            period: "/orang/bulan",
            description: "Untuk tim yang butuh alur kerja dan pelaporan lebih rapi.",
            features: ["Proyek tanpa batas", "Timeline dan dependensi", "Laporan otomatis", "Dukungan prioritas"],
            buttonText: "Coba Flow",
            buttonUrl: "#mulai",
            highlighted: true,
          },
          {
            name: "Scale",
            price: "Hubungi kami",
            period: "",
            description: "Untuk organisasi dengan kebutuhan integrasi dan kontrol khusus.",
            features: ["SAML / SSO", "Hak akses khusus", "Onboarding tim", "Pendampingan migrasi"],
            buttonText: "Hubungi tim",
            buttonUrl: "#kontak",
            highlighted: false,
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "startup-stories",
      componentType: "testimonial-grid",
      name: "Cerita Pengguna Orbitly",
      props: {
        eyebrow: "Cerita pelanggan",
        title: "Tim yang baik tidak perlu bekerja keras untuk tetap sinkron.",
        description: "Orbitly menyesuaikan diri dengan ritme tim, bukan memaksa tim mengikuti sistem yang kaku.",
        columns: "3",
        items: [
          {
            quote: "Kami berhenti bertanya ‘yang mengerjakan ini siapa?’ karena semuanya langsung terlihat tanpa membuka banyak chat.",
            name: "Bagas Santosa",
            role: "Head of Product, Pijar",
            initials: "BS",
          },
          {
            quote: "Yang paling terasa bukan fiturnya, tapi ruang napas yang muncul karena tim lebih jarang mengejar update satu sama lain.",
            name: "Dina Putri",
            role: "Operations Lead, Habitus",
            initials: "DP",
          },
          {
            quote: "Kami bisa melihat pekerjaan yang macet lebih awal, sehingga pelanggan tidak lagi menerima kabar terlambat.",
            name: "Raka Wirawan",
            role: "Founder, Kawan Kerja",
            initials: "RW",
          },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "startup-faq",
      componentType: "faq-accordion",
      name: "FAQ Orbitly",
      props: {
        eyebrow: "Pertanyaan sebelum mulai",
        title: "Hal kecil yang biasanya ingin ditanyakan tim baru.",
        description: "Mulai dari satu proyek, undang tim, dan lihat apakah ritmenya terasa lebih baik.",
        items: [
          { question: "Apakah saya perlu memasang aplikasi?", answer: "Tidak perlu. Orbitly nyaman dipakai langsung dari browser, lalu dapat ditambahkan ke layar ponsel bila dibutuhkan." },
          { question: "Bisa dipakai untuk tim non-teknis?", answer: "Bisa. Bahasa dan alurnya dibuat untuk pekerjaan sehari-hari—kampanye, proyek klien, operasi, atau produk." },
          { question: "Bagaimana jika tim sudah punya banyak spreadsheet?", answer: "Mulai dari satu alur yang paling sering dipakai. Tim kami dapat membantu memetakan perpindahan secara bertahap." },
          { question: "Apakah data tim aman?", answer: "Kami memakai kontrol akses per workspace dan riwayat perubahan supaya informasi selalu berada di tangan orang yang tepat." },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "startup-cta",
      componentType: "cta-basic",
      name: "Ajakan Mulai Orbitly",
      props: {
        title: "Berikan tim Anda satu tempat yang benar-benar dipakai bersama.",
        description: "Coba selama 14 hari tanpa kartu kredit. Bawa satu proyek nyata, lalu lihat perbedaannya.",
        buttonText: "Mulai 14 hari gratis",
        buttonUrl: "#mulai",
        secondaryText: "Jadwalkan demo",
        secondaryUrl: "#kontak",
      },
      styles: { padding: "xl" },
    },
    {
      id: "startup-footer",
      componentType: "footer-basic",
      name: "Footer Orbitly",
      props: {
        brandName: "orbitly",
        tagline: "Ruang kerja bersama untuk tim yang ingin bergerak dengan lebih jernih.",
        link1Text: "Fitur",
        link1Url: "#fitur",
        link2Text: "Harga",
        link2Url: "#harga",
        link3Text: "halo@orbitly.id",
        link3Url: "mailto:halo@orbitly.id",
        copyrightText: "© 2026 Orbitly. Dibuat untuk tim yang bekerja bersama.",
      },
      styles: { padding: "none" },
    },
  ];
}
