import type { RawTemplateNode } from "@/templates";

/** Studio kreatif & digital — terinspirasi dari template "made". */
export function createStudioKreatifNodes(): RawTemplateNode[] {
  return [
    {
      id: "made-nav",
      componentType: "navbar-mega",
      name: "Navigasi Studio Made",
      props: {
        logoText: "made studio",
        menuText: "Layanan",
        linkText: "Tentang",
        linkUrl: "#tentang",
        ctaText: "Diskusi proyek",
        ctaUrl: "#kontak",
        columns: [
          { heading: "Desain", link1Label: "Identitas visual", link1Url: "#layanan", link2Label: "Desain produk", link2Url: "#layanan", link3Label: "Ilustrasi", link3Url: "#layanan" },
          { heading: "Digital", link1Label: "Website", link1Url: "#layanan", link2Label: "Aplikasi mobile", link2Url: "#layanan", link3Label: "Kampanye", link3Url: "#layanan" },
        ],
      },
      styles: { padding: "none" },
    },
    {
      id: "made-hero",
      componentType: "hero-split",
      name: "Hero Made Studio",
      props: {
        badgeText: "Studio kreatif dengan 60+ penghargaan",
        title: "Warna, bentuk, dan cerita yang dibuat dengan sengaja.",
        description:
          "Made adalah studio desain dan pengembangan di Yogyakarta. Kami membantu brand Indonesia tampil berani dan konsisten — dari identitas hingga produk digital yang benar-benar diluncurkan.",
        primaryCtaText: "Diskusi proyek",
        primaryCtaUrl: "#kontak",
        secondaryCtaText: "Lihat karya",
        secondaryCtaUrl: "#karya",
        imageUrl:
          "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Tim studio sedang meninjau desain di dinding besar",
        supportingText: "Bekerja sama dengan 80+ brand sejak 2016.",
        imageBadgeText: "YOGYAKARTA",
        imageNoteLabel: "Studio kami",
        imageNoteText: "20 orang kreatif di satu lantai eks-bengkel.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "made-layanan",
      componentType: "grid-container",
      name: "Layanan Made",
      props: { columns: "3", gap: "md" },
      styles: { padding: "xl", background: "muted" },
      children: [
        {
          id: "made-layanan-1",
          componentType: "card-feature",
          name: "Identitas & Strategi",
          props: {
            icon: "sparkles",
            eyebrow: "Strategi",
            title: "Identitas yang lahir dari riset, bukan tebakan.",
            description: "Riset brand, arsitektur merek, dan sistem visual yang siap digunakan di semua kanal.",
            linkText: "Selengkapnya",
            linkUrl: "#kontak",
          },
        },
        {
          id: "made-layanan-2",
          componentType: "card-feature",
          name: "Produk Digital",
          props: {
            icon: "layers",
            eyebrow: "Digital",
            title: "Produk digital yang diuji ke pengguna nyata.",
            description: "Desain dan pengembangan aplikasi web & mobile dengan standar kualitas yang bisa diaudit.",
            linkText: "Selengkapnya",
            linkUrl: "#kontak",
          },
        },
        {
          id: "made-layanan-3",
          componentType: "card-feature",
          name: "Gerakan Brand",
          props: {
            icon: "megaphone",
            eyebrow: "Kampanye",
            title: "Kampanye yang membuat orang berhenti scroll.",
            description: "Konsep kreatif, produksi visual, dan materi kampanye untuk peluncuran yang berkesan.",
            linkText: "Selengkapnya",
            linkUrl: "#kontak",
          },
        },
      ],
    },
    {
      id: "made-statistik",
      componentType: "stats-banner",
      name: "Statistik Made",
      props: {
        eyebrow: "Hasil yang bisa dihitung",
        title: "Angka yang kami kumpulkan dari proyek sejak 2016.",
        sectionBg: "primary",
        stats: [
          { value: "80+", suffix: "", label: "brand yang pernah bekerja sama" },
          { value: "60+", suffix: "", label: "penghargaan desain nasional" },
          { value: "240", suffix: "+", label: "proyek selesai tepat waktu" },
          { value: "92%", suffix: "", label: "klien kembali untuk proyek berikutnya" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "made-karya",
      componentType: "gallery-grid",
      name: "Karya Terbaru",
      props: {
        sectionId: "karya",
        eyebrow: "Karya terbaru",
        title: "Proyek yang baru kami selesaikan.",
        description: "Kurasi karya dari kuartal terakhir — identitas, produk digital, dan kampanye.",
        columns: "3",
        images: [
          {
            url: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1200&q=85",
            title: "Rebrand Rumah Rempah",
            caption: "Identitas & kemasan · 2026",
            alt: "Kemasan rempah dengan warna hangat",
          },
          {
            url: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=1200&q=85",
            title: "Aplikasi Jurnal",
            caption: "Desain produk · 2026",
            alt: "Antarmuka aplikasi jurnal digital",
          },
          {
            url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=85",
            title: "Website Geulis",
            caption: "Desain & pengembangan · 2025",
            alt: "Tim bekerja di depan layar website",
          },
          {
            url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=85",
            title: "Kampanye Keramik Loka",
            caption: "Kampanye peluncuran · 2025",
            alt: "Materi kampanye produk keramik",
          },
          {
            url: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=85",
            title: "Identitas Tani Kita",
            caption: "Sistem visual · 2025",
            alt: "Papan identitas perusahaan pertanian",
          },
          {
            url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=85",
            title: "Aplikasi Sapa",
            caption: "Desain produk · 2024",
            alt: "Antarmuka aplikasi di layar ponsel",
          },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "made-tim",
      componentType: "team-grid",
      name: "Tim Inti",
      props: {
        eyebrow: "Tim",
        title: "Orang-orang di balik studio.",
        description: "Sebagian dari tim inti yang menangani proyek dari brief hingga peluncuran.",
        columns: "4",
        members: [
          { name: "Gita Maharani", role: "Direktur kreatif", initials: "GM", socialUrl: "#" },
          { name: "Fajar Ramadhan", role: "Strategi brand", initials: "FR", socialUrl: "#" },
          { name: "Sari Wulandari", role: "Desain produk", initials: "SW", socialUrl: "#" },
          { name: "Aditya Nugraha", role: "Teknikal lead", initials: "AN", socialUrl: "#" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "made-kontak",
      componentType: "form-contact",
      name: "Form Proyek Baru",
      props: {
        eyebrow: "Proyek baru",
        heading: "Ceritakan proyek yang ingin Anda wujudkan.",
        subheading: "Isi beberapa hal dasar. Kami undang Anda ngobrol di studio atau via panggilan video dalam satu minggu.",
        email: "halo@madestudio.id",
        nameLabel: "Nama Anda",
        namePlaceholder: "Contoh: Hana Permata",
        emailLabel: "Email",
        emailPlaceholder: "nama@email.com",
        messageLabel: "Ceritakan proyek Anda",
        messagePlaceholder: "Jenis proyek, target waktu, dan anggaran…",
        buttonText: "Kirim ringkasan proyek",
        note: "Kami membalas semua pesan maksimal 1×24 jam kerja.",
        successText: "Ringkasan proyek diterima. Kami akan menghubungi Anda untuk langkah berikutnya.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "made-footer",
      componentType: "footer-basic",
      name: "Footer Made",
      props: {
        brandName: "made studio",
        tagline: "Studio kreatif di Yogyakarta. Jl. Kaliurang KM 5, No. 21. Buka Senin–Jumat 09.00–18.00.",
        link1Text: "Karya",
        link1Url: "#karya",
        link2Text: "Tentang",
        link2Url: "#tentang",
        link3Text: "halo@madestudio.id",
        link3Url: "mailto:halo@madestudio.id",
        copyrightText: "© 2026 Made Studio Kreatif.",
      },
      styles: { padding: "none" },
    },
    {
      id: "made-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}