import type { RawTemplateNode } from "@/templates";

/** Agen perjalanan dengan paket wisata, cara pesan, testimoni wisatawan, dan FAQ. */
export function createTravelLandingNodes(): RawTemplateNode[] {
  return [
    {
      id: "travel-nav",
      componentType: "navbar-glass",
      name: "Navigasi Biru Samudra",
      props: {
        logoText: "BIRU SAMUDRA",
        link1Text: "Paket",
        link1Url: "#paket",
        link2Text: "Cara pesan",
        link2Url: "#cara-pesan",
        link3Text: "Ulasan",
        link3Url: "#ulasan",
        ctaText: "Hubungi agen",
        ctaUrl: "#kontak",
      },
      styles: { padding: "none" },
    },
    {
      id: "travel-hero",
      componentType: "hero-centered",
      name: "Hero Biru Samudra",
      props: {
        badgeText: "Paket domestik & internasional",
        title: "Liburan yang diatur detailnya oleh orang yang pernah ke sana.",
        description:
          "Biru Samudra menyusun paket wisata Bali, Yogyakarta, Labuan Bajo, hingga Lombok sejak 2012. Setiap paket sudah termasuk hotel, transportasi, dan pemandu lokal berbahasa Indonesia.",
        primaryCtaText: "Lihat paket",
        primaryCtaUrl: "#paket",
        secondaryCtaText: "Hubungi agen",
        secondaryCtaUrl: "#kontak",
        imageUrl:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88",
        imageAlt: "Pantai berpasir putih dengan air laut yang jernih",
        supportingText: "Berizin Kemenparekraf · Kantor di Bandung",
        imageBadgeText: "SINCE 2012",
      },
      styles: { padding: "xl" },
    },
    {
      id: "travel-paket",
      componentType: "product-grid-basic",
      name: "Paket Wisata",
      props: {
        sectionId: "paket",
        sectionTitle: "Enam paket yang paling banyak diberangkatkan bulan ini.",
        sectionSubtitle:
          "Harga per orang untuk minimal dua peserta, sudah termasuk hotel bintang sesuai paket, transportasi, dan pemandu lokal.",
        productsJson: JSON.stringify([
          {
            id: "bali-3d2n",
            name: "Bali 3D2N",
            price: "Rp 1,9 juta",
            tag: "Terlaris",
            description: "Hotel bintang 3 di Kuta, transfer bandara, dan tour Ubud–Tanah Lot.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "yogyakarta-2d1n",
            name: "Yogyakarta 2D1N",
            price: "Rp 850 ribu",
            tag: "Paket singkat",
            description: "Malioboro, Candi Borobudur, dan hotel di kawasan kota.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "labuan-bajo-4d3n",
            name: "Labuan Bajo 4D3N",
            price: "Rp 4,2 juta",
            tag: "Kapal phinisi",
            description: "Pulau Komodo, Padar, dan snorkeling dengan kapal phinisi standar.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "lombok-3d2n",
            name: "Lombok 3D2N",
            price: "Rp 1,7 juta",
            tag: "Pantai selatan",
            description: "Selong Belanak, Gili Trawangan, dan hotel di Senggigi.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "malang-2d1n",
            name: "Malang 2D1N",
            price: "Rp 950 ribu",
            tag: "Gunung & apel",
            description: "Bromo sunrise dari Cemoro Lawang dan wisata kota Batu.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=900&q=84",
          },
          {
            id: "bandung-2d1n",
            name: "Bandung 2D1N",
            price: "Rp 780 ribu",
            tag: "Paling terjangkau",
            description: "Tangkuban Perahu, kawah Putih, dan hotel di Lembang.",
            actionText: "Lihat detail",
            actionUrl: "#kontak",
            imageUrl: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=84",
          },
        ]),
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "travel-stats",
      componentType: "stats-banner",
      name: "Statistik Biru Samudra",
      props: {
        eyebrow: "Catatan keberangkatan kami",
        title: "Angka yang kami hitung dari tiket yang benar-benar terbit.",
        sectionBg: "primary",
        stats: [
          { value: "4.800", suffix: "+", label: "tamu diberangkatkan tiap tahun" },
          { value: "12", suffix: " tahun", label: "melayani sejak 2012" },
          { value: "30", suffix: "+", label: "destinasi domestik & internasional" },
          { value: "4,8", suffix: " / 5", label: "rating dari 2.300 ulasan" },
        ],
      },
      styles: { padding: "xl" },
    },
    {
      id: "travel-cara",
      componentType: "process-steps",
      name: "Cara Pesan Biru Samudra",
      props: {
        eyebrow: "Cara pesan",
        heading: "Tiga langkah, lalu tinggal berangkat.",
        stepsJson: JSON.stringify([
          {
            id: "t1",
            title: "Pilih paket",
            description: "Tentukan destinasi dan tanggal. Agen kami bantu sesuaikan bila rombongan lebih dari 10 orang.",
          },
          {
            id: "t2",
            title: "Bayar DP 30%",
            description: "Sisanya dilunasi 14 hari sebelum keberangkatan, lewat transfer atau cicilan kartu kredit.",
          },
          {
            id: "t3",
            title: "Berangkat",
            description: "Tiket, itinerary, dan kontak pemandu dikirim 7 hari sebelum hari-H.",
          },
        ]),
      },
      styles: { padding: "xl" },
    },
    {
      id: "travel-testimoni",
      componentType: "testimonial-grid",
      name: "Testimoni Wisatawan",
      props: {
        eyebrow: "Kata wisatawan",
        title: "Mereka yang pulang membawa cerita, bukan keluhan.",
        description: "Kutipan dari ulasan Google dan pesan WhatsApp yang kami minta izin untuk ditampilkan.",
        columns: "3",
        items: [
          { quote: "Paket Bali 3D2N pas di budget kantor. Hotelnya bersih dan pemandunya menjelaskan sejarah tiap spot.", name: "Rina Marlina", role: "Karyawan swasta, Jakarta", initials: "RM" },
          { quote: "Rombongan kantor 24 orang ke Yogyakarta diurus sampai detail tiket kereta. Semua berjalan lancar.", name: "Bayu Prasetyo", role: "HRD, Bekasi", initials: "BP" },
          { quote: "Saya batal karena sakit, jadwal diganti tanpa biaya tambahan. Agennya cepat di WhatsApp.", name: "Dewi Anggraini", role: "Surabaya", initials: "DA" },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "travel-ulasan",
      componentType: "social-proof",
      name: "Rating Biru Samudra",
      props: {
        rating: 5,
        ratingText: "4,8 dari 5",
        countText: "2.300+ ulasan Google & TripAdvisor",
        note: "Berdiri sejak 2012 di Bandung dengan pemandu lokal di setiap destinasi. Berizin Kemenparekraf No. 098/D.3/2012.",
      },
      styles: { padding: "xl" },
    },
    {
      id: "travel-faq",
      componentType: "faq-accordion",
      name: "FAQ Biru Samudra",
      props: {
        eyebrow: "Pertanyaan umum",
        title: "Pembatalan, asuransi, dan pembayaran.",
        description: "Masih ragu? Telepon (022) 423-7810, kami jawab tanpa juru bicara berbelit.",
        items: [
          { question: "Bagaimana jika saya harus membatalkan perjalanan?", answer: "Pembatalan lebih dari 30 hari sebelum keberangkatan: DP dikembalikan 80%. Kurang dari itu, jadwal bisa diganti tanggal atau nama tanpa biaya." },
          { question: "Apakah paket termasuk asuransi perjalanan?", answer: "Paket di atas Rp 2 juta sudah termasuk asuransi perjalanan dasar. Tambahan asuransi full dapat dibeli sebesar Rp 75.000 per orang." },
          { question: "Metode pembayaran apa saja?", answer: "Transfer bank, virtual account BCA dan Mandiri, serta cicilan 0% kartu kredit tenor 3 bulan." },
          { question: "Apakah pemandu lokal berbahasa Indonesia?", answer: "Ya. Semua pemandu kami berbahasa Indonesia dan menguasai rute kunjungan, termasuk jalur alternatif saat macet." },
        ],
      },
      styles: { padding: "xl", background: "muted" },
    },
    {
      id: "travel-cta",
      componentType: "cta-basic",
      name: "Ajakan Rencanakan Liburan",
      props: {
        title: "Rencanakan liburan Anda bersama agen yang pernah ke sana.",
        description: "Konsultasi gratis setiap hari 08.00–20.00 WIB lewat telepon atau WhatsApp. Diskon grup mulai 10 orang.",
        buttonText: "Hubungi agen",
        buttonUrl: "#kontak",
        secondaryText: "Lihat paket",
        secondaryUrl: "#paket",
      },
      styles: { padding: "xl" },
    },
    {
      id: "travel-footer",
      componentType: "footer-basic",
      name: "Footer Biru Samudra",
      props: {
        brandName: "BIRU SAMUDRA",
        tagline: "Agen perjalanan resmi sejak 2012. Kantor di Jl. Diponegoro No. 45, Bandung.",
        link1Text: "Paket",
        link1Url: "#paket",
        link2Text: "Hubungi",
        link2Url: "#kontak",
        link3Text: "(022) 423-7810",
        link3Url: "tel:+62224237810",
        copyrightText: "© 2026 Biru Samudra Tour & Travel.",
      },
      styles: { padding: "none" },
    },
    {
      id: "travel-backtotop",
      componentType: "back-to-top",
      name: "Kembali ke Atas",
      props: {
        label: "Kembali ke atas",
        position: "right",
        showAfter: 320,
        variant: "solid",
      },
      styles: { padding: "none" },
    },
  ];
}
