import type { ComponentManifest } from "@/lib/registry/types";

export const formContactManifest: Omit<ComponentManifest, "previewRenderer" | "exportAdapter"> = {
  id: "form-contact",
  name: "Form Kontak",
  category: "form",
  scope: "landing",
  description: "Form kontak lengkap dengan nama, email, pesan, serta konfirmasi berhasil yang ringan.",
  tier: "free",
  priceKey: "form-contact",
  version: "2.0.0",
  defaultProps: {
    eyebrow: "Konsultasi 30 menit",
    heading: "Ceritakan apa yang ingin Anda bangun.",
    subheading: "Isi beberapa hal dasar. Kami balas maksimal 1×24 jam kerja dengan rekomendasi yang sesuai lingkup proyek Anda.",
    email: "halo@karsastudio.id",
    nameLabel: "Nama Anda",
    namePlaceholder: "Contoh: Nadia Kurnia",
    emailLabel: "Email kerja",
    emailPlaceholder: "nama@perusahaan.com",
    messageLabel: "Ceritakan proyek Anda",
    messagePlaceholder: "Saya ingin membuat website untuk…",
    buttonText: "Kirim pesan",
    note: "Dengan mengirim formulir ini, Anda setuju untuk dihubungi kembali.",
    successText: "Pesan Anda sudah kami terima. Sampai bertemu di percakapan berikutnya.",
  },
  contentControls: [
    { key: "eyebrow", label: "Label kecil", group: "Header", type: "text" },
    { key: "heading", label: "Judul", group: "Header", type: "text" },
    { key: "subheading", label: "Penjelasan", group: "Header", type: "textarea" },
    { key: "email", label: "Email yang ditampilkan", group: "Kontak", type: "text" },
    { key: "nameLabel", label: "Label nama", group: "Formulir", type: "text" },
    { key: "namePlaceholder", label: "Contoh nama", group: "Formulir", type: "text" },
    { key: "emailLabel", label: "Label email", group: "Formulir", type: "text" },
    { key: "emailPlaceholder", label: "Contoh email", group: "Formulir", type: "text" },
    { key: "messageLabel", label: "Label pesan", group: "Formulir", type: "text" },
    { key: "messagePlaceholder", label: "Contoh pesan", group: "Formulir", type: "textarea" },
    { key: "buttonText", label: "Teks tombol", group: "Formulir", type: "text" },
    { key: "note", label: "Catatan kecil", group: "Formulir", type: "textarea" },
    { key: "successText", label: "Pesan berhasil", group: "Formulir", type: "textarea" },
  ],
};
