import type { ExportResult } from "@/lib/registry/types";
import type { Node } from "@/lib/schema/types";
import { escapeHtml, propString, sanitizeUrl } from "@/lib/registry/shared";
import { directNavigationLinks, navInstanceId } from "../_shared/navigation";
import { logoMarkHtml } from "../_shared/logo-export";

export function navbarSplitExport(node: Node): ExportResult {
  const logo = propString(node, "logoText").trim() || "Ruang Rasa";
  const cta = propString(node, "ctaText").trim() || "Belanja sekarang";
  const ctaUrl = sanitizeUrl(propString(node, "ctaUrl").trim() || "#koleksi");
  const instance = navInstanceId(node, "split-nav");
  const menuId = `${instance}-menu`;
  const links = directNavigationLinks(node, 3).map((link) => `<a class="bi-split-link" href="${escapeHtml(link.url)}">${escapeHtml(link.label)}</a>`).join("");
  return {
    html: `<header class="bi-split-wrap"><nav class="bi-split-nav" data-bi-split-nav="${instance}" data-open="false" aria-label="Navigasi utama"><a class="bi-split-brand" href="#">${logoMarkHtml(node, logo, "bi-split-brand-img", "", undefined, true)}${escapeHtml(logo)}</a><div class="bi-split-links">${links}<a class="bi-split-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">↗</span></a></div><button data-bi-split-toggle class="bi-split-toggle" type="button" aria-label="Buka menu" aria-expanded="false" aria-controls="${menuId}"><i></i><i></i></button><div class="bi-split-mobile" id="${menuId}">${links}<a class="bi-split-mobile-cta" href="${escapeHtml(ctaUrl)}">${escapeHtml(cta)} <span aria-hidden="true">↗</span></a></div></nav></header>`,
    css: `.bi-split-wrap{position:relative;z-index:20;padding:1rem 1.5rem;background:var(--bi-bg);color:var(--bi-fg);font-family:var(--bi-font-body)}.bi-split-nav{position:relative;display:flex;max-width:72rem;align-items:center;justify-content:space-between;gap:1.25rem;margin:auto;padding-bottom:.75rem;border-bottom:1px solid var(--bi-border)}.bi-split-brand{display:inline-flex;align-items:center;gap:.5rem;color:var(--bi-fg);font-family:var(--bi-font-heading);font-size:1.28rem;font-weight:900;letter-spacing:-.065em;text-decoration:none}.bi-split-brand-img{width:2rem;height:2rem;border-radius:var(--bi-radius);object-fit:cover}.bi-split-links{display:flex;align-items:center;gap:1.65rem}.bi-split-link{position:relative;padding:.4rem 0;color:var(--bi-muted-fg);font-size:.88rem;font-weight:650;text-decoration:none;transition:color .2s ease}.bi-split-link::after{position:absolute;right:0;bottom:0;left:0;height:1px;transform:scaleX(0);transform-origin:left;background:var(--bi-primary);content:"";transition:transform .2s ease}.bi-split-link:hover{color:var(--bi-fg)}.bi-split-link:hover::after{transform:scaleX(1)}.bi-split-cta,.bi-split-mobile-cta{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;padding:.7rem 1rem;border-radius:999px;background:var(--bi-primary);color:var(--bi-primary-fg);font-size:.76rem;font-weight:800;text-decoration:none;transition:transform .2s ease}.bi-split-cta:hover,.bi-split-mobile-cta:hover{transform:translateY(-2px)}.bi-split-toggle,.bi-split-mobile{display:none}@media(max-width:720px){.bi-split-wrap{padding:.85rem 1rem}.bi-split-links{display:none}.bi-split-toggle{display:grid;width:2.25rem;height:2.25rem;place-content:center;gap:.28rem;border:1px solid var(--bi-border);border-radius:50%;background:transparent;color:var(--bi-fg);cursor:pointer}.bi-split-toggle i{display:block;width:.95rem;height:1.5px;background:currentColor;transition:transform .2s ease}.bi-split-nav[data-open="true"] .bi-split-toggle i:first-child{transform:translateY(2px) rotate(45deg)}.bi-split-nav[data-open="true"] .bi-split-toggle i:last-child{transform:translateY(-2px) rotate(-45deg)}.bi-split-nav[data-open="true"] .bi-split-mobile{position:absolute;top:calc(100% + .65rem);right:0;left:0;display:grid;gap:.15rem;padding:.5rem;border:1px solid var(--bi-border);border-radius:var(--bi-radius);background:var(--bi-card);box-shadow:var(--bi-shadow)}.bi-split-mobile .bi-split-link{padding:.72rem .75rem;border-radius:calc(var(--bi-radius) * .75)}.bi-split-mobile .bi-split-link::after{display:none}.bi-split-mobile .bi-split-link:hover{background:var(--bi-muted)}.bi-split-mobile-cta{margin-top:.25rem;border-radius:calc(var(--bi-radius) * .75);padding:.82rem}}`,
    js: `document.querySelectorAll('[data-bi-split-nav="${instance}"]').forEach(function(nav){var button=nav.querySelector('[data-bi-split-toggle]');if(!button)return;button.addEventListener('click',function(){var open=nav.dataset.open==='true';nav.dataset.open=String(!open);button.setAttribute('aria-expanded',String(!open));button.setAttribute('aria-label',open?'Buka menu':'Tutup menu');});nav.querySelectorAll('.bi-split-mobile a').forEach(function(link){link.addEventListener('click',function(){nav.dataset.open='false';button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Buka menu');});});});`,
  };
}
